// Blood
index = 4;

TSW.Wheel[index].cells.push({
	"name": "Profane",
	"tier": "1",
	"abilities": [
		{
			"name": "Boiling Blood",
			"gid": 6391342,
			"iid": 6814152,
			"background": 5,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"build": "1",
			"target": "Single",
			"description": "Builds $r1 resource for each weapon type.<br>A single target attack that deals $d48 magical damage.",
		},
		{
			"name": "Corrupted Blood",
			"gid": 6408197,
			"iid": 6814193,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Boiling Blood",
			"apply": "Afflict",
			"description": "Whenever you hit with \"Boiling Blood,\" the target also becomes $sAfflicted with a damage over time effect that deals $d2 magical damage every second for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Blood Spike",
			"gid": 6391526,
			"iid": 6814151,
			"background": 5,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1.5",
			"consume": "2",
			"apply": "Afflict",
			"target": "Single",
			"description": "Consumes $r2 Blood Resources. Can be powered by your own health.<br>A single target attack that deals $d88 magical damage and also causes the target to become $sAfflicted with a damage over time effect that deals $d8 magical damage every $t0.5 seconds for $t5 seconds.<br> <br>If your target has the \"Blood Spike\" damage over time effect already, this ability instead deals $d188 magical damage.",
		},
		{
			"name": "Dark Potency",
			"gid": 6399902,
			"iid": 6814194,
			"background": 6,
			"cost": 2,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Afflict",
			"apply": "Penetrate",
			"description": "Whenever you apply $sAfflicted, you gain a single stack of the Penetration Rating effect, which increases Penetration Rating by $c40 per stack for for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Infection",
			"gid": 6391777,
			"iid": 6814154,
			"background": 5,
			"cost": 3,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1.5",
			"consume": "3",
			"apply": "Chain,Afflict",
			"target": "Chain",
			"description": "$uChain: Jumps up to $c5 metres $c5 times, hitting up to $c6 enemies.<br>Consumes $r3 Blood Resources. Can be powered by your own health.<br>A $uChain attack that deals $d53 magical damage. Affected targets also become $sAfflicted with a damage over time effect dealing $d7 magical damage every $t2 seconds for $t12 seconds. If an enemy dies while affected by this effect, it explodes, dealing $d40 magical damage to nearby targets.",
		},
		{
			"name": "Thicker than Water",
			"gid": 6428150,
			"iid": 6814195,
			"background": 6,
			"cost": 4,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"apply": "Damage",
			"description": "Increases the damage and healing of blood abilities by $t10%.",
		},
		{
			"name": "Cardiac Arrest",
			"gid": 6391980,
			"iid": 6814153,
			"background": 5,
			"cost": 7,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "25",
			"react": "Anima Deviation",
			"apply": "Impair,Vulnerable",
			"target": "Single",
			"description": "A single target attack that deals $d345 magical damage. The target also becomes $sImpaired and unable to act for $t3 seconds.<br> <br>Applies $sVulnerable to Melee. <br> <br>Susceptible to $sAnima Deviation.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Sacred",
	"tier": "1",
	"abilities": [
		{
			"name": "Unholy Knowledge",
			"gid": 6389443,
			"iid": 6814199,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"description": "Increase damage dealt by damage over time effects by $t10%.",
		},
		{
			"name": "Blood Shield",
			"gid": 6391460,
			"iid": 6814156,
			"background": 3,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"apply": "Heal,Barrier",
			"target": "Single",
			"description": "Builds $r1 Blood Resource.<br>Heals $h27 and places an absorb barrier on your defensive target. This barrier absorbs $h100% of incoming damage and dissipates after absorbing $h26 damage.",
		},
		{
			"name": "Rapid Shield",
			"gid": 6410713,
			"iid": 6814198,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Blood Shield",
			"description": "Increases the heal and barrier of \"Blood Shield\" by $t7.5%.",
		},
		{
			"name": "Angelic Aegis",
			"gid": 6554318,
			"iid": 6814155,
			"background": 3,
			"cost": 2,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1.5",
			"consume": "3",
			"apply": "Heal,Barrier",
			"target": "Single",
			"description": "Consumes $r3 Blood resources. Can be powered by your own health.<br>Heals $h104 and places an absorb barrier on your defensive target. This barrier absorbs $h100% of incoming damage and dissipates after absorbing $h104 damage.",
		},
		{
			"name": "Angel's Touch",
			"gid": 6427031,
			"iid": 6814196,
			"background": 6,
			"cost": 3,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Angelic Aegis",
			"description": "\"Angelic Aegis\" heals for an additional $h46 to targets below $t50% health.",
		},
		{
			"name": "Exsanguinate",
			"gid": 6391945,
			"iid": 6814157,
			"background": 5,
			"cost": 4,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "2.5",
			"consume": "5",
			"react": "Impair",
			"apply": "Focus,Afflict",
			"target": "Single",
			"description": "Channelled: Every $t0.5 seconds for $t2.5 seconds.<br>Consumes $r5 Blood Resources. Can be powered by your own health.<br>A channeled $uFocus attack that deals $d61 magical damage per hit. If the target is $sImpaired, it also becomes $sAfflicted with a damage over time effect that deals $d6 magical damage every second for $t10 seconds.",
		},
		{
			"name": "Coagulation",
			"gid": 6429797,
			"iid": 6814197,
			"background": 6,
			"cost": 7,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"react": "Barrier",
			"description": "Increases the effectiveness of barrier effects by $t60%.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Malediction",
	"tier": "2",
	"abilities": [
		{
			"name": "Bloodline",
			"gid": 6943079,
			"iid": 7653178,
			"background": 5,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"build": "1",
			"apply": "Focus",
			"target": "Single",
			"description": "Channelled: Every $t0.25 seconds for $t1 second.<br>Builds $r1 resource for each equipped weapon.<br>A channelled $uFocus attack that deals $d12 magical damage per hit.",
		},
		{
			"name": "Iron Maiden",
			"gid": 6943080,
			"iid": 7519462,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Penetrate,Afflict",
			"apply": "Penetrate",
			"description": "Whenever you penetrate a target that is $sAfflicted, you gain a Minor Penetration Chance effect, which increases Penetration Chance by $c15% for $t8 seconds.",
		},
		{
			"name": "Left Hand of Darkness",
			"gid": 6943081,
			"iid": 7653180,
			"background": 5,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"consume": "3",
			"apply": "Afflict,Impair",
			"target": "Single",
			"description": "Consumes $r3 Blood Resources. Can be powered by your own health.<br>Causes the target to become $sAfflicted with a damage over time effect that deals $d34 magical damage every second for $t4 seconds. If you hit the target with this ability again while the effect is active, the target becomes $sImpaired and unable to act for $t1 second. This ability will apply a $t30 second cooldown when the stun is applied.",
		},
		{
			"name": "Prolonged Darkness",
			"gid": 6943082,
			"iid": 7653212,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Left Hand of Darkness",
			"description": "The \"Left Hand of Darkness\" damage over time effect lasts $t2 seconds longer.",
		},
		{
			"name": "Bloodshot",
			"gid": 6943083,
			"iid": 7653179,
			"background": 5,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "2",
			"react": "Afflict",
			"target": "Single",
			"description": "Consumes $r2 Blood Resources. Can be powered by your own health.<br>A single target attack that deals $d117 magical damage, or $d129 magical damage if the target is $sAfflicted.",
		},
		{
			"name": "Torture",
			"gid": 6943084,
			"iid": 7519460,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Focus",
			"description": "Whenever you finish channelling a $uFocus attack, you perform an extra hit that deals $d8 magical damage to the target.",
		},
		{
			"name": "Plague",
			"gid": 6943085,
			"iid": 7653181,
			"background": 5,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cast": "1.5",
			"cooldown": "20",
			"apply": "Afflict,Vulnerable",
			"target": "Single",
			"description": "A single target attack that causes the target to become $sAfflicted with a damage over time effect that deals $d65 magical damage every $t2 seconds for $t12 seconds.<br> <br>If the target dies while the Plague damage over time effect is active, enemies within $c7 metres will become $sAfflicted with a new damage over time effect that deals $d34 magical damage every $t2 seconds for $t8 seconds.<br> <br>Applies $sVulnerable to Ranged.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Transmission",
	"tier": "2",
	"abilities": [
		{
			"name": "Vital Fluids",
			"gid": 6943089,
			"iid": 7519454,
			"background": 6,
			"cost": 9,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Afflict",
			"apply": "Resource",
			"description": "Whenever you apply $sAfflicted, you have a $t17.5% chance of building $r1 resource for your primary weapon. If you already have the maxiumum available resources when this effect triggers, you will instead perform an additional hit dealing $d21 magical damage to the target.",
		},
		{
			"name": "Anaesthesia",
			"gid": 6943090,
			"iid": 7653182,
			"background": 5,
			"cost": 12,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "60",
			"apply": "Impair",
			"target": "Single",
			"description": "A single target attack that deals $d91 magical damage and causes the target to become $sImpaired and unable to act for $t5 seconds. This ability has a $c3 metre range.",
		},
		{
			"name": "Third Degree",
			"gid": 6943091,
			"iid": 7519456,
			"background": 6,
			"cost": 16,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Penetrate",
			"apply": "Afflict",
			"description": "Whenever you penetrate, you build a Third Degree counter. When this counter reaches $t3, you also cause the target to become $sAfflicted with a damage over time effect that deals $d23 magical damage every second for $t4 seconds.",
		},
		{
			"name": "Contaminate",
			"gid": 6943092,
			"iid": 7653184,
			"background": 5,
			"cost": 21,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"cooldown": "40",
			"apply": "Afflict",
			"target": "Single",
			"description": "A single target attack that causes the target to become $sAfflicted by a damage over time effect that deals $d20 magical damage every second for $t6 seconds. If the target is healed while this damage over time effect is active, it will perform a hit on the healer that deals $d60 magical damage.",
		},
		{
			"name": "Blood Bank",
			"gid": 6943093,
			"iid": 7519458,
			"background": 6,
			"cost": 27,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Afflict",
			"description": "Whenever you apply $sAfflicted, you gain a stack of Blood Bank effect, which increases the damage dealt by your damage over time effects by $t3% per stack for $t10 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Cannibalise",
			"gid": 6943094,
			"iid": 7653183,
			"background": 4,
			"cost": 34,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "25",
			"build": "3",
			"description": "Builds $r3 Blood Resources.<br>Deals $d10% of your maximum health as magical damage to you and grants a beneficial effect that causes you next Blood resource consumer to deal $t20% more damage. This ability does not trigger and is not affected by global recharge time.",
		},
		{
			"name": "Gross Anatomy",
			"gid": 6943095,
			"iid": 7519457,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"react": "Afflict",
			"description": "Whenever one of your damage over time effects expires or is renewed, it will perform an additional hit that deals $d21 magical damage.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Possession",
	"tier": "2",
	"abilities": [
		{
			"name": "Open Vein",
			"gid": 6943139,
			"iid": 7653187,
			"background": 5,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "0.5",
			"build": "1",
			"apply": "Chain",
			"target": "Chain",
			"description": "Chain: Jumps up to $c5 metres $c5 times, hitting up to $c6 enemies.<br>Builds $r1 resource for each equipped weapon.<br>A $uChain attack that deals $d24 magical damage.",
		},
		{
			"name": "Doom",
			"gid": 6943140,
			"iid": 7519450,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Penetrate",
			"apply": "Penetrate",
			"description": "Whenever you penetrate, you gain a Doom counter. When this counter reaches $t4, your next hit will penetrate.",
		},
		{
			"name": "There Will Be Blood",
			"gid": 6943141,
			"iid": 7653188,
			"background": 5,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "5",
			"target": "GTAoE",
			"description": "GTAoE: Affects $c6 enemies in a $c5 metre radius around the targeted point.<br>Consumes $r5 Blood Resources. Can be powered by your own health.<br>A GTAoE attack that deals $d53 magical damage. Also places an area on the ground lasting $t6 seconds. This area deals $d5 magical damage every second to enemies inside it, scaling with the number of targets originally hit.",
		},
		{
			"name": "Splatter",
			"gid": 6943142,
			"iid": 7519449,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Chain",
			"description": "All your $uChain attacks can jump to $c2 additional targets.",
		},
		{
			"name": "Guts and Gory",
			"gid": 6943143,
			"iid": 7653186,
			"background": 5,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "3",
			"react": "Impair",
			"apply": "Penetrate",
			"target": "TAoE",
			"description": "TAoE: Affects up to $c6 enemies in a $c5 metre radius around the target.<br>Consumes $r3 Blood resources. Can be powered by your own health.<br>A TAoE attack that deals $d70 magical damage. If any target is $sImpaired, you gain the Major Penetration Chance effect, which increases your Penetration Chance by $c45% for $t6 seconds.",
		},
		{
			"name": "Circulation",
			"gid": 6943144,
			"iid": 7519452,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Afflict,Impair",
			"apply": "HoT,Barrier",
			"description": "Whenever you apply $sAfflicted, you gain a heal over time effect that heals for $h7 every second for $t10 seconds. If the target is $sImpaired, the effect will also give you a barrier that absorbs $h100% of incoming damage and dissipates after absorbing $h15 damage.",
		},
		{
			"name": "Expulsion",
			"gid": 6943145,
			"iid": 7653185,
			"background": 5,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "20",
			"apply": "Barrier",
			"description": "Places an absorb barrier on you that absorbs $h100% of incoming damage and dissipates after absorbing $h244 damage. This barrier scales with Attack Rating and not with Healing Rating. When the barrier either expires or is spent, it will deal $d311 magical damage to all enemies within $t5 metres of you.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Wetwork",
	"tier": "2",
	"abilities": [
		{
			"name": "Ruby Curtain",
			"gid": 6956304,
			"iid": 7653191,
			"background": 3,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"apply": "Heal,Barrier",
			"target": "Single",
			"description": "Builds $r1 Blood Resource.<br>A single target heal that heals for $h11 and places an absorb barrier on your defensive target. This barrier absorbs $h100% of incoming damage and dissipates after absorbing $h42 damage.",
		},
		{
			"name": "Donor",
			"gid": 6956305,
			"iid": 7519446,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Penetrate",
			"apply": "Barrier",
			"description": "Whenever you penetrate, you place a barrier on your defensive target. This barrier absorbs $h100% of incoming damage and dissipates after absorbing $h15 damage.",
		},
		{
			"name": "The Scarlet Arts",
			"gid": 6956306,
			"iid": 7653192,
			"background": 3,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "2",
			"consume": "5",
			"apply": "Heal,Barrier",
			"target": "Single",
			"description": "Channelling: Every $t0.4 seconds for $t2 seconds.<br>Consumes $r5 Blood Resources. Can be powered by your own health.<br>The first channelling hit places an absorb barrier on your defensive target, which absorbs $h100% of incoming damage and dissipates after absorbing $h57. The next $t3 channelling hits heal the defensive target for $h58. The last channelling hit places the same barrier as the first hit.",
		},
		{
			"name": "Culmination",
			"gid": 6956307,
			"iid": 7519448,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Focus",
			"apply": "Heal",
			"description": "Whenever you finish channelling a $uFocus ability, you heal your defensive target for $h9.",
		},
		{
			"name": "Exquisite Corpse",
			"gid": 6956308,
			"iid": 7653189,
			"background": 3,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "2",
			"apply": "Heal,Barrier",
			"target": "Single",
			"description": "Consumes $r2 Blood Resources. Can be powered by your own health.<br>Places a reflect barrier on your defensive target, which reflects $h50% of incoming damage back to the attacker and dissipates after reflecting $h67 damage. Also heals the defensive target for $h61.",
		},
		{
			"name": "Sanguineous",
			"gid": 6956309,
			"iid": 7519444,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Barrier",
			"apply": "Heal",
			"description": "Whenever you place a barrier, you are healed for $h11.",
		},
		{
			"name": "My Bloody Valentine",
			"gid": 6956310,
			"iid": 7653190,
			"background": 3,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cast": "1",
			"cooldown": "20",
			"apply": "Heal,Barrier",
			"description": "Places an absorb barrier on your defensive target, which absorbs $h100% of incoming damage and dissipates after absorbing $h228 damage.<br> <br>While this barrier is active, you are healed for $h44 every second. When the barrier is removed it deals $d224 damage in a $c5 metre area around the target.<br> <br>If any enemies are hit by this, you gain a barrier that absorbs $h100% of incoming damage and dissipates after absorbing $h152 damage.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Chirurgia",
	"tier": "2",
	"abilities": [
		{
			"name": "Omen",
			"gid": 6956311,
			"iid": 7519437,
			"background": 6,
			"cost": 9,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Impair",
			"apply": "Barrier",
			"description": "Whenever you apply $sImpaired or whenever you are $sImpaired, you gain a beneficial effect that increases the amount of damage you next barrier can absorb by $h100.",
		},
		{
			"name": "Transfuse and Abuse",
			"gid": 6956330,
			"iid": 7653195,
			"background": 4,
			"cost": 12,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "20",
			"apply": "Cleanse,Afflict",
			"description": "Cleanses up to $t3 damage over time effects active on you, and causes the target to become $sAfflicted with a damage over time effect that deals $d9 magical damage every second per effect you cleansed for $t7 seconds. This ability can only be activated when you are $sAfflicted.",
		},
		{
			"name": "Five Times a Charm",
			"gid": 6956329,
			"iid": 7519440,
			"background": 6,
			"cost": 16,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Penetrate",
			"apply": "Impair",
			"description": "Whenever you penetrate, you build a Five Times a Charm counter. When this counter reaches $t5, it will cause the target to become $sImpaired and unable to act for $t3 seconds. This effect has a recharge time of $t30 seconds.",
		},
		{
			"name": "Liquidation",
			"gid": 6956328,
			"iid": 7653194,
			"background": 5,
			"cost": 21,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"apply": "Afflict,Heal",
			"description": "Places an area around the targeted point that will last $t10 seconds. Enemies inside the area become $sAfflicted with a damage over time effect that deals $d14 magical damage and heals you for $h7 every second for $t4 seconds.",
		},
		{
			"name": "Ebb and Flow",
			"gid": 6956327,
			"iid": 7519441,
			"background": 6,
			"cost": 27,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"apply": "Barrier",
			"description": "Increases the power of your barriers by $t20%, but reduces the power of your direct heals by $t5%.",
		},
		{
			"name": "Infusion",
			"gid": 6956326,
			"iid": 7653193,
			"background": 4,
			"cost": 34,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"build": "3",
			"apply": "Barrier",
			"description": "Builds $r3 Blood Resources.<br>You remove your own barrier and gain a beneficial effect that will cause your next barrier to absorb $h35% more damage. This ability can only be activated when you have a barrier. This ability does not trigger and is not affected by global recharge time.",
		},
		{
			"name": "Clotting",
			"gid": 6956325,
			"iid": 7519442,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"react": "Barrier",
			"description": "Whneever you apply a barrier to a target that already has a barrier, you also heal the target for $t67% of the new barrier's strength.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Venamancy",
	"tier": "2",
	"abilities": [
		{
			"name": "Hematic Rites",
			"gid": 6956324,
			"iid": 7653198,
			"background": 3,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "2",
			"apply": "Barrier",
			"target": "TAoE",
			"description": "TAoE: Affects up to $t6 friends within a $t5 metre radius around the defensive target.<br>Consumes $r2 Blood resources. Can be powered by your own health.<br>Places an absorb barrier on all affected targets, which absorbs $h100% of incoming damage and dissipates after absorbing $h67 damage.",
		},
		{
			"name": "Arterial Pulse",
			"gid": 6956323,
			"iid": 7519435,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Penetrate",
			"description": "Whenever you penetrate, you perform an additional hit on the target and enemies around it that deals $d14 magical damage.",
		},
		{
			"name": "Linked Veins",
			"gid": 6956322,
			"iid": 7653199,
			"background": 3,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"apply": "Chain,Heal,Barrier",
			"target": "Chain",
			"description": "$uChain: Jumps up to $c5 metres $c5 times, hitting up to $c6 friends.<br>Builds $r1 Blood resource.<br>A $uChain that heals for $h13 and places a barrier that absorbs $h100% of incoming damage and dissipates after absorbing $h13 damage. This effect does not apply to self.",
		},
		{
			"name": "Last Rites",
			"gid": 6956321,
			"iid": 7519433,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Hematic Rites",
			"description": "TAoE: Affects up to $t6 friends and enemies in a $t5 metre radius around the target.<br>Improves \"Hematic Rites\" to deal $d10 magical damage to nearby enemies if the barrier expires, or is depleted. \"Hermetic Rites\" also now heals for $h17 and places a barrier that absorbs $h100% of incoming damage and dissipates after absorbing $h67 damage instead of its normal effects.",
		},
		{
			"name": "Blood Pact",
			"gid": 6956320,
			"iid": 7653196,
			"background": 3,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"consume": "5",
			"apply": "Barrier,Impair",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 friends in a $c5 metre radius around you.<br>Consumes $r5 Blood Resources. Can be powered by your own health.<br>Places an absorb barrier on affected targets that absorbs $h100% of incoming damage and dissipates after absorbing $h78 damage. Affected targets are also given a beneficial effect that causes the first enemy to hit them to become $sImpaired and unable to act for $t3 seconds.",
		},
		{
			"name": "Vessel Walls",
			"gid": 6956319,
			"iid": 7653213,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Chain",
			"apply": "Barrier",
			"description": "Whenever you activate a $uChain ability, you gain an absorb barrier that absorbs $h100% of incoming damage and dissipates after absorbing $h26 damage.",
		},
		{
			"name": "Cold Blooded",
			"gid": 6956318,
			"iid": 7653197,
			"background": 3,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cast": "2",
			"cooldown": "30",
			"apply": "Heal,Barrier",
			"target": "Group",
			"description": "Channelled: Every $t0.5 seconds for $t2 seconds.<br>You deal $d3% of your maximum health as magical damage to yourself. Each team member is healed $h67 per tick and receives an absorb barrier. This barrier absorbs $h100% of incoming damage and dissipates after absorbing $h66 damage. While you channel, you take $t40% less damage.",
		},
	]
});
