// Chaos
index = 5;

TSW.Wheel[index].cells.push({
	"name": "Theory",
	"tier": "1",
	"abilities": [
		{
			"name": "Hand of Change",
			"gid": 6388280,
			"iid": 6814160,
			"background": 5,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"target": "Single",
			"description": "Builds $r1 resource for each equipped weapon.<br>A single target attack that deals $d48 magical damage",
		},
		{
			"name": "Entropy",
			"gid": 6389445,
			"iid": 6814201,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Hand of Change",
			"react": "Critical,Penetrate",
			"apply": "Resource",
			"description": "Whenever you critically hit or penetrate with \"Hand of Change\" it Builds $r1 additional Chaos Resource.",
		},
		{
			"name": "Call for Eris",
			"gid": 6388361,
			"iid": 6814158,
			"background": 5,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"apply": "Burst",
			"target": "Single",
			"description": "Consumes all Chaos Resources.<br>A $uBurst attack that deals $d69 magical damage. Also performs an additional hit per resource consumed, dealing $d22-23 magical damage per hit. Damage of the additional hits scales based on the number of resources consumed.",
		},
		{
			"name": "Paradigm Shift",
			"gid": 6399186,
			"iid": 6814202,
			"background": 6,
			"cost": 2,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Weaken",
			"apply": "Hit",
			"description": "Whenever you apply $sWeakened, you have a $t30% chance to gain the Minor Hit Chance effect, which reduces the chance of glancing by $t10% for $t8 seconds.",
		},
		{
			"name": "Schism",
			"gid": 6388986,
			"iid": 6814161,
			"background": 5,
			"cost": 3,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"target": "Single",
			"description": "Consumes all Chaos Resources.<br>A single target attack that deals $d83-165 magical damage, or $d103-204 magical damage if the target has below $t35% remaining health. Damage scales based on the number of resources consumed.",
		},
		{
			"name": "Chaos Adept",
			"gid": 6390189,
			"iid": 6814200,
			"background": 6,
			"cost": 4,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"apply": "Damage",
			"description": "Increases the damage dealt by Chaos abilities by $t10%.",
		},
		{
			"name": "Domino Effect",
			"gid": 6389397,
			"iid": 6814159,
			"background": 5,
			"cost": 7,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "25",
			"apply": "Impair",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 enemies in a $c7 metre area around you.<br>A PBAoE attack that damages and pulls affected targets towards you. Affected targets also become $sImpaired and are knocked to the ground. The range, amount of damage dealt, and imparement duration of this ability are based on the number of targets hit and the range at which they are hit:<br> <br>• Prompt Critical Event: When only one enemy is within $c3 metres this ability deals $d345 damage and Impairs for $c1 second.<br> <br>• Double-Six Quantum Pieces: When one enemy is within $c3 metres and a second is within $c5 metres this ability deals $d311 damage and Impairs for $c3 seconds.<br> <br>• Cascading Boneyard: When at least one enemy is within $c3 metres, a second is within $c5 metres, and a third is within $c7 metres this ability deals $d293 damage and Impairs for $c4 seconds.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Chance",
	"tier": "1",
	"abilities": [
		{
			"name": "Gnosis",
			"gid": 6513280,
			"iid": 6814203,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Weaken",
			"description": "Whenever you hit a $sWeakened target, there is a $t33% chance to perform an additional hit dealing $d21 magical damage.",
		},
		{
			"name": "Escalation",
			"gid": 6388290,
			"iid": 6814162,
			"background": 5,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"apply": "Frenzy,Hate",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 enemies in a $c5 metre area around you.<br>Builds $r1 resource for each equipped weapon.<br>A PBAoE $uFrenzy ability that deals $d24 magical damage. Generates a high amount of hate.",
		},
		{
			"name": "Intensity",
			"gid": 6390136,
			"iid": 6814204,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Escalation",
			"apply": "Weaken,Hate,Hit",
			"description": "Improves \"Escalation\" by reducing the chance that it will glance by $t5%, increasing the hate it generates by $t20%, and it will also cause affected targets to become $sWeakened by a single stack of the Exposed effect, which increases all damage received by $t2% per stack for $t10 seconds. Exposed can stack up to $t10 times.",
		},
		{
			"name": "Illusion",
			"gid": 6388427,
			"iid": 6814163,
			"background": 4,
			"cost": 2,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "45",
			"apply": "Evade",
			"description": "You gain the Major Evade Chance effect, which increases your Evade Chance by $t35% for $t6 seconds. This ability does not trigger and is not affected by global recharge time.",
		},
		{
			"name": "Master of Illusions",
			"gid": 6390152,
			"iid": 6814205,
			"background": 6,
			"cost": 3,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Illusion",
			"apply": "Evade",
			"description": "\"Illusion\" instead gives you a beneficial effect that increases your Evade Chance by $t45% for $t8 seconds.",
		},
		{
			"name": "Paradox",
			"gid": 6389379,
			"iid": 6814164,
			"background": 5,
			"cost": 4,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "10",
			"react": "Impair",
			"target": "Single",
			"description": "A single target attack that deals $d86 magical damage, or $d116 magical damage if the target is $sImpaired.",
		},
		{
			"name": "Probability",
			"gid": 6390191,
			"iid": 6814206,
			"background": 6,
			"cost": 7,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"react": "Evade,Hit",
			"apply": "Damage",
			"description": "Whenever you evade, gain the Major Ward effect, which reduces all damage received by $t25% for $t6 seconds.<br>Whenever you hit $t3 times in a row, you gain a beneficial effect that increases all damage dealt by $t8% for $t10 seconds.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Teorama",
	"tier": "2",
	"abilities": [
		{
			"name": "Deconstruct",
			"gid": 7094297,
			"iid": 7465878,
			"background": 5,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"target": "Single",
			"description": "Builds $r1 resource for each equipped weapon.<br>A single target attack that deals $d46 magical damage. Builds $r2 resources if the target is below $t35% health.",
		},
		{
			"name": "Cutting Thoughts",
			"gid": 7094296,
			"iid": 7465837,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Hit",
			"description": "Whenever you hit, you build a Cutting Thoughts counter. When there are $t5 counters, your next hit performs an additional $t3 hits, dealing $d14 magical damage per hit. If you perform a glancing hit, the counter will be reset.",
		},
		{
			"name": "Four Horsemen",
			"gid": 7094295,
			"iid": 7465877,
			"background": 5,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"react": "Hit",
			"apply": "Burst",
			"target": "Single",
			"description": "Consumes all Chaos Resources.<br>A single target $uBurst that hits $t4 times, dealing $d21-41 magical damage per hit, based on the number of resources consumed. Each hit causes the next hit to deal more damage, this bonus stops if a hit glances.",
		},
		{
			"name": "Ripple Effect",
			"gid": 7094294,
			"iid": 7465856,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Burst,Hit",
			"description": "Whenever 2 hits in a row of a $uBurst attack do not glance, your next attack will perform an additional hit dealing $d8 magical damage.",
		},
		{
			"name": "Pulling the Strings",
			"gid": 7094293,
			"iid": 7465868,
			"background": 5,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"react": "Weaken",
			"apply": "Hit",
			"target": "Single",
			"description": "Consumes all Chaos Resources<br>A single target attack with a $c7 metre range that deals $d86-174 magical damage, based on the number of resources consumed. If the target is $sWeakened, you gain the Minor Hit Chance effect, which reduces the chance of glancing hits by $t10% for $t8 seconds.",
		},
		{
			"name": "Pale Horse",
			"gid": 7094292,
			"iid": 7465855,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Pulling the Strings",
			"description": "Improves \"Pulling the Strings\" and \"Four Horsemen\" to deal $t30% more damage to targets with less than $t35% health remaining.",
		},
		{
			"name": "Prisoner of Fate",
			"gid": 7094291,
			"iid": 7465875,
			"background": 5,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cast": "5",
			"cooldown": "20",
			"apply": "Vulnerable",
			"target": "Single",
			"description": "Channelled: Every second $t5 seconds.<br>A channelled attack that deals $d151 magical damage per hit, or $d214 magical damage if the target's health is below $t35%.<br> <br>This ability has a $c7 metre range.<br> <br>Applies $sVulnerable to Melee. ",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "The Value of x",
	"tier": "2",
	"abilities": [
		{
			"name": "Breakdown",
			"gid": 7094290,
			"iid": 7465854,
			"background": 6,
			"cost": 9,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Hit",
			"apply": "Weaken",
			"description": "Whenever you hit a target with a Chaos, Blade or Hammer ability, it becomes $sWeakened by a single stack of the Exposed effect, which increase all damage received by $t2% per stack for $t10 seconds. Exposed can stack up to $t10 times.",
		},
		{
			"name": "Amor Fati",
			"gid": 7094289,
			"iid": 7465863,
			"background": 4,
			"cost": 12,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "60",
			"apply": "Hit,Damage",
			"description": "Gives you a beneficial effect that increases all damage dealt by $d10%. Your attacks cannot glance or be evaded. This effect lasts $t10 seconds. This ability does not trigger and is not affected by global recharge time.",
		},
		{
			"name": "Pressure Point",
			"gid": 7094288,
			"iid": 7465853,
			"background": 6,
			"cost": 16,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"apply": "Impair",
			"description": "Whenever you attack, you build a Pressure Point counter. When there are $t6 counters, your next attack will cause your target to become $sImpaired and knocked to the ground for $t3 seconds. The counter is then reset. This effect has an internal recharge time of $t30 seconds.",
		},
		{
			"name": "Helter Skelter",
			"gid": 7094287,
			"iid": 7465873,
			"background": 5,
			"cost": 21,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "35",
			"apply": "Impair,Movement",
			"target": "Column",
			"description": "Column Dash: Dash forward $c10 metres, affecting up to $c6 enemies in a $c6 metre wide column along the way.<br>A column dash attack the deals $d66 physical damage. Affected targets become $sImpaired and unable to act for $t3 seconds.",
		},
		{
			"name": "Pattern Recognition",
			"gid": 7094286,
			"iid": 7465852,
			"background": 6,
			"cost": 27,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Impair",
			"description": "Whenever you hit an $sImpaired target, you perform an additional hit for $d42 magical damage. This has a $t15% chance of performing an additional hit for the same damage.",
		},
		{
			"name": "Discord Rising",
			"gid": 7094285,
			"iid": 7465872,
			"background": 5,
			"cost": 34,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"apply": "Weaken",
			"target": "AoE",
			"description": "Creates a $c10 metre radius area at your feet, which will move $c10 metres forward over $t1.5 seconds. The area will deal $d54 magical damage to all enemies it touches on its way, and also causes them to become $sWeakened by $t3 stacks of the Exposed effect. This effect increases all damage received by $t2% per stack for $t8 seconds, and can stack up to $t10 times.",
		},
		{
			"name": "From the Abyss",
			"gid": 7094284,
			"iid": 7465851,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"description": "Whenever you hit, you build a From the Abyss counter. When there are $t3 counters, you deal $d50 magical damage to up to $c6 enemies in a $c5 metre radius around you, or $d65 magical damage to targets that have less than $t35% health remaining.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Collapse",
	"tier": "2",
	"abilities": [
		{
			"name": "Wheel of Knives",
			"gid": 7094283,
			"iid": 7465871,
			"background": 5,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"apply": "Frenzy",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 enemies in a $c5 metre radius around you.<br>Builds $r1 Resource for each equipped weapon.<br>A $uFrenzy attack dealing $d24 magical damage.",
		},
		{
			"name": "Wheel of Misfortune",
			"gid": 7094282,
			"iid": 7465850,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Wheel of Knives",
			"react": "Weaken,Impair",
			"description": "\"Wheel of Knives\" performs an additional hit to $sWeakened and $sImpaired targets, dealing $d6 magical damage.",
		},
		{
			"name": "Maelstrom",
			"gid": 7094281,
			"iid": 7465870,
			"background": 5,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"target": "PBAoE",
			"description": "PBAoE: Which affects up to $c6 enemies in a $c5 metre radius around the area around you.<br>Consumes all Chaos resources.<br>A PBAoE attack that deals $d45-89 magical damage.",
		},
		{
			"name": "Hysteria",
			"gid": 7094280,
			"iid": 7465849,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Frenzy",
			"apply": "Hit",
			"description": "Whenever you hit with a $uFrenzy attack, you gain a single stack of the Hit Rating effect, which increases Hit Rating by $c40 per stack for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Cry Havoc",
			"gid": 7094279,
			"iid": 7465869,
			"background": 5,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"react": "Impair",
			"target": "TAoE",
			"description": "TAoE: Which affects up to $c6 enemies in a $c5 metre radius around your target.<br>Consumes all Chaos Resources.<br>A TAoE attack that deals $d41-85 magic damage, based on the number of resources consumed. If any target in the affected area is $sImpaired, it creates a damaging ground area at their feet which deals $d9 magical damage every second for $t5 seconds.",
		},
		{
			"name": "Sick Society",
			"gid": 7094278,
			"iid": 7465848,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"description": "Whenever you attack a target below $t35% health, you perform an additional hit that deals $d20 magical damage.",
		},
		{
			"name": "Eye of Pandemonium",
			"gid": 7094277,
			"iid": 8934511,
			"background": 5,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "25",
			"react": "Anima Deviation",
			"apply": "Hinder,Impair,Vulnerable",
			"target": "Single",
			"description": "A single target attack that deals $d276 magical damage and causes the target to become $sHindered and rooted to the ground for $t4 seconds.<br> <br>For the next $t10 seconds, up to $c6 enemies between $c1 and $c7 metres of the target will be dealt $d14 magical damage each second and have a $c30% chance to become $sImpaired as they are knocked into the air.<br> <br>Applies $sVulnerable to Ranged. <br> <br>Susceptible to $sAnima Deviation.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Building Blocks",
	"tier": "2",
	"abilities": [
		{
			"name": "Run Rampant",
			"gid": 7094276,
			"iid": 7465867,
			"background": 5,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"apply": "Burst,Evade",
			"target": "Single",
			"description": "Builds $r1 resource for each equipped weapon.<br>A single target $uBurst that hits $t3 times, dealing $d15 magical damage per hit. Gives you a single stack of the Evade Rating effect, which increases your Evade Rating by $c40 per stack for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Inevitability",
			"gid": 7094275,
			"iid": 7465847,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Weaken",
			"apply": "Evade",
			"description": "Whenever a $sWeakened target attacks you, you have a $t15% chance to gain the Minor Evade Chance effect, which increases the Evade Chance by $t10% for $t8 seconds.",
		},
		{
			"name": "Consequence",
			"gid": 7094274,
			"iid": 7465866,
			"background": 5,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"apply": "Weaken",
			"description": "Consumes all Chaos resources.<br>A single target attack that deals $d69-157 magical damage, based on the number of resources consumed. Gives you the Minor Ward effect, that reduces all damage received by $t7.5% for $t8 seconds. Also gives you another beneficial effect that causes the next hit against you to deal $d20 magical damage back to the attacker, who becomes $sWeakened by $t1 stack of the Exposed effect. Exposed increases all damage received by $t2% per stack for $t10 seconds and can stack up to $t10 times.",
		},
		{
			"name": "Burst of Energy",
			"gid": 7094273,
			"iid": 7465846,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Burst",
			"description": "Damaging $uBurst abilities give you the Minor Ward effect if at least $t2 hits do not glance, which reduces all damage received by $t7.5% for $t8 seconds.",
		},
		{
			"name": "Suffering and Solace",
			"gid": 7094272,
			"iid": 7465865,
			"background": 5,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"react": "Impair",
			"target": "Single",
			"description": "Consumes all Chaos Resources.<br>A single target attack that deals $d90-178 magical damage, based on the number of resources consumed. If the target is $sImpaired, you also gain a beneficial effect causing the next $t3 hits against you to reflect $d3% per resource of the damage dealt back at the attacker.",
		},
		{
			"name": "Fever Pitch",
			"gid": 7094271,
			"iid": 7465845,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Weaken",
			"apply": "Hit",
			"description": "Whenever you hit a $sWeakened target, you have a $t15% chance to gain the Major Hit Chance effect, which reduces the chance of glancing by $t25% for $t5 seconds.",
		},
		{
			"name": "Immutable",
			"gid": 7094270,
			"iid": 7465864,
			"background": 4,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "60",
			"description": "Gives you a beneficial effect that causes you to be immortal for $t6 seconds. When this effect expires, you heal for $h30% of your maximum health.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Shell Game",
	"tier": "2",
	"abilities": [
		{
			"name": "Fixation",
			"gid": 7080752,
			"iid": 7465844,
			"background": 6,
			"cost": 9,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Weaken",
			"apply": "Hit",
			"description": "Whenever you hit a $sWeakened target, you have a $t50% chance to gain a single stack of the Hit Rating effect, which increases Hit Rating by $c40 per stack for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Chaotic Pull",
			"gid": 7080753,
			"iid": 7465874,
			"background": 5,
			"cost": 12,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "35",
			"apply": "Impair",
			"target": "Single",
			"description": "A single attack that deals $d91 magical damage and the target becomes $sImpaired as they are pulled toward you. This ability has a $c15 metre range.",
		},
		{
			"name": "Contradiction",
			"gid": 7080754,
			"iid": 7465843,
			"background": 6,
			"cost": 16,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Defense,Block,Evade",
			"apply": "Weaken",
			"description": "Whenever you are glanced, you evade, or block an attack, your attacker becomes $sWeakened by $t2 stacks of the Exposed effect, which increases all damage received by $t2% per stack for $t10 seconds. This effect can stack up to $t10 times.",
		},
		{
			"name": "Uneven Ground",
			"gid": 7080755,
			"iid": 7465862,
			"background": 5,
			"cost": 21,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "45",
			"apply": "Weaken,Evade",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 enemies in a $c5 metre radius around you.<br>A PBAoE attack that deals $d51 magical damage. Affected targets also become $sWeakened by $t5 stacks for the Exposed effect, which increases all damage received by $t2% per stack for $t10 seconds. This effect can stack up to $t10 times. For each target affected, you gain a single stack of the Evade Rating effect, which increases your Evade Rating by $c40 per stack for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Cause and Effect",
			"gid": 7080756,
			"iid": 7465842,
			"background": 6,
			"cost": 27,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Impair",
			"apply": "Hate",
			"description": "Whenever you apply $sImpaired or whenever you are $sImpaired, you gain a beneficial effect that causes your next attack to deal $t15% additional damage and the target generates $c1250 extra hate towards you.",
		},
		{
			"name": "Smoke and Mirrors",
			"gid": 7080757,
			"iid": 7465861,
			"background": 4,
			"cost": 34,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "90",
			"apply": "Evade",
			"description": "Gives you a beneficial effect that increases Evade Chance by $t40% for $t8 seconds. This ability does not trigger and is not affected by global recharge time.",
		},
		{
			"name": "Prodigal",
			"gid": 7094303,
			"iid": 7465841,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"description": "Increases maximum health by $h10%. Base duration of crowd control effects applied to you are reduced by $t35%.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "The Fourth Wall",
	"tier": "2",
	"abilities": [
		{
			"name": "Shaken Foundations",
			"gid": 7080758,
			"iid": 7465841,
			"background": 5,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"target": "TAoE",
			"description": "TAoE: Affects $c6 enemies in a $c5 metre radius around you.<br>Builds $r1 resource for each equipped weapon.<br>A TAoE that deals $d24 magical damage.",
		},
		{
			"name": "Backlash",
			"gid": 7094305,
			"iid": 7465840,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Evade",
			"description": "Whenever you evade, you build a Backlash counter. When there are $t7 counters, you deal $d108 magical damage in an area around you and reset the counter. Up to a maximum of $t5 targets.",
		},
		{
			"name": "Karma",
			"gid": 7080759,
			"iid": 7465859,
			"background": 5,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "4",
			"consume": "-1",
			"apply": "Frenzy",
			"target": "PBAoE",
			"description": "PBAoE: Affects $c6 enemies in a $c5 metre radius around you.<br>Consumes all Chaos Resources.<br>A PBAoE $uFrenzy attack that deals $d40-80 magical damage, based on the number of resources consumed. Also applies a detrimental effect to affected targets that causes them to heal the next target they hit for a percentage of their target's maximum health.",
		},
		{
			"name": "Turbulence",
			"gid": 7094307,
			"iid": 7465839,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Frenzy",
			"apply": "Evade",
			"description": "Whenever you activate a $uFrenzy ability, you gain a single stack of the Evade Rating effect, which increases your Evade Rating by $c40 per stack for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Reality Fracture",
			"gid": 7080760,
			"iid": 7465858,
			"background": 5,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "10",
			"react": "Weaken",
			"apply": "Hate",
			"target": "GTAoE",
			"description": "GTAoE: Affects up to $c6 enemies in a $c5 metre radius around the target point, pulsing every second for $t6 seconds.<br>Consumes all Chaos Resources.<br>A GTAoE that deals $d11-21 magical damage, or $d12-25 physical damage if the target is $sWeakened. Damage scales based on the number of resources consumed. This attack generates a high amount of hate.",
		},
		{
			"name": "Extended Fracture",
			"gid": 7094310,
			"iid": 7465838,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Reality Fracture",
			"description": "\"Reality Fracture\" deals $t15% more damage and affects $t2 more targets.",
		},
		{
			"name": "Gravitational Anomaly",
			"gid": 7080761,
			"iid": 8934510,
			"background": 5,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cast": "3",
			"cooldown": "25",
			"target": "PBAoE",
			"description": "Channelled: Every second for $t3 seconds.<br>PBAoE: Affects up to $c3 random enemies in a $c10 metre radius.<br>A channelled PBAoE attack that deals $d175 magical damage per hit.<br> <br>Affected targets become $sImpaired and knocked into the air for $t2 seconds.",
		},
	]
});
