// Hammer
index = 2;

TSW.Wheel[index].cells.push({
	"name": "Brawn",
	"tier": "1",
	"abilities": [
		{
			"name": "Smash",
			"gid": 6347465,
			"iid": 6814389,
			"background": 2,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"target": "Single",
			"description": "Builds $r1 resource for each equipped weapon.<br>A single target attack that deals $d48 physical damage.",
		},
		{
			"name": "Below the Belt",
			"gid": 6347548,
			"iid": 6814393,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Smash",
			"apply": "Weaken",
			"description": "Whenever you hit with \"Smash\", the target also becomes $sWeakened by a single stack of the Debilitated effect, which reduces all damage dealt by $t3% per stack for $t10 seconds. The effect can stack up to $t10 times.",
		},
		{
			"name": "Hell to Pay",
			"gid": 6335423,
			"iid": 6814387,
			"background": 2,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"apply": "Blast",
			"target": "Column",
			"description": "Column: Affects up to $c6 enemies in a $c4 metre wide by $c5 metre long area in front of you.<br>Consumes all hammer resources.<br>A column $uBlast attack that deals $d49-98 physical damage, based on the number of resources consumed.",
		},
		{
			"name": "Righteous Fury",
			"gid": 6347573,
			"iid": 6814395,
			"background": 6,
			"cost": 2,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Hell to Pay",
			"apply": "Critical",
			"description": "Increases the critical chance of your \"Hell to Pay\" ability by $t15%.",
		},
		{
			"name": "Haymaker",
			"gid": 6347472,
			"iid": 6814386,
			"background": 2,
			"cost": 3,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"react": "Impair",
			"apply": "Strike",
			"target": "Single",
			"description": "Consumes all Hammer Resources.<br>A single target $uStrike attack that deals $d90-178 physical damage, or $d103-205 physical damage if the target is $sImpaired. Damage scales based on the number of resources consumed.",
		},
		{
			"name": "Hard Impact",
			"gid": 6368936,
			"iid": 6814394,
			"background": 6,
			"cost": 4,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"apply": "Damage",
			"description": "Increases the damage you do with your Hammer abilities by $t10%.",
		},
		{
			"name": "Shockwave",
			"gid": 6347479,
			"iid": 6814388,
			"background": 2,
			"cost": 7,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "25",
			"apply": "Impair,Vulnerable",
			"target": "Column",
			"description": "Column: Affects up to $c6 enemies in a $c4 metre wide by $c8 metre long area in front of you.<br>A Column attack that deals $d345 physical damage. Affected targets also become $sImpaired and knocked to the ground for $t3 seconds.<br> <br>Applies $sVulnerable to Magic.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Grit",
	"tier": "1",
	"abilities": [
		{
			"name": "Brawler",
			"gid": 6368910,
			"iid": 6814396,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical",
			"description": "Increases Crit Power by $t15%.",
		},
		{
			"name": "Grand Slam",
			"gid": 6347501,
			"iid": 6814391,
			"background": 2,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"react": "Weaken",
			"apply": "Hate",
			"target": "Single",
			"description": "Builds $r1 resource for each equipped weapon.<br>A single target attack that deals $d45 physical damage. If you hit a $sWeakened target, an AoE that deals $d7 physical damage appears, effecting up to $c6 enemies in a $c5 metre radius around your target. This additional damage generates a large amount of hate towards you.",
		},
		{
			"name": "Street Fighter",
			"gid": 6368918,
			"iid": 6814399,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Impair",
			"description": "Whenever you apply $sImpaired, you gain a beneficial effect that increases all damage dealt by $t10% for $t8 seconds.",
		},
		{
			"name": "Stonewalled",
			"gid": 6347528,
			"iid": 6814392,
			"background": 4,
			"cost": 2,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "45",
			"apply": "Block",
			"description": "You gain the Major Block Chance Effect, which increases your Block Chance by $c45% for $t6 seconds. This ability does not trigger and is not affected by global recharge time.",
		},
		{
			"name": "Stone Cold",
			"gid": 6368893,
			"iid": 6814398,
			"background": 6,
			"cost": 3,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Stonewalled",
			"description": "Reduces the recharge time of \"Stonewalled\" by $t15 seconds.",
		},
		{
			"name": "Backhanded",
			"gid": 6347476,
			"iid": 6814390,
			"background": 2,
			"cost": 4,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "5",
			"build": "2",
			"apply": "Resource",
			"target": "Single",
			"description": "Builds $r2 Hammer Resources if you have no Hammer Resources.<br>A single target attack that deals $d55 physical damage.",
		},
		{
			"name": "Cool, Calm & Collected",
			"gid": 6368906,
			"iid": 6814397,
			"background": 6,
			"cost": 7,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"react": "Block,Critical",
			"apply": "Damage",
			"description": "Whenever you block an attack, you gain the Major Ward effect, which reduces all damage received by $c25% for $t6 seconds. Whenever you critically hit, you gain a beneficial effect that increases all damage dealt by $t8% for $t10 seconds.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Industrial Action",
	"tier": "2",
	"abilities": [
		{
			"name": "First Blood",
			"gid": 6837785,
			"iid": 7070870,
			"background": 2,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"apply": "Strike",
			"target": "Single",
			"description": "Builds $r1 resource for each equipped weapon.<br>A single target $uStrike attack that deals $d47 physical damage, or $d55 physical damage if you have no Hammer Resources.",
		},
		{
			"name": "Soft Target",
			"gid": 6861824,
			"iid": 7076269,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical,Impair",
			"apply": "Resource",
			"description": "Whenever you critically hit an $sImpaired target, the next resource builder you activate builds $r3 additional resource for your primary weapon.",
		},
		{
			"name": "Molten Steel",
			"gid": 6837799,
			"iid": 7070871,
			"background": 2,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"react": "Critical",
			"target": "Single",
			"description": "Consumes all Hammer Resources.<br>A single target attack that deals $d86-171 physical damage, based on the number of resources consumed. Deals $c15% additional critical damage. This attack has a $c30% additional chance to critically hit.",
		},
		{
			"name": "Wrecking Crew",
			"gid": 6861825,
			"iid": 7076267,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Strike",
			"apply": "Critical",
			"description": "Increase the Crit Power of $uStrike attacks by $t20%.",
		},
		{
			"name": "Bone Breaker",
			"gid": 6837812,
			"iid": 7070868,
			"background": 2,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"react": "Weaken",
			"target": "Single",
			"description": "Consumes all Hammer Resources.<br>A single target attack that deals $d86-171 physical damage, or $d95-188 physical damage if the target is $sWeakened. Damage scales based on the number of resources consumed.",
		},
		{
			"name": "Metal Worker",
			"gid": 6861826,
			"iid": 7076268,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Molten Steel",
			"description": "\"Molten Steel\" no longer gains additional Critical Damage. Instead, \"Molten Steel\" now performs an additional hit that deals $d4-113 physical damage, based on the number of resources consumed. The amount of damage scales with your maximum health.",
		},
		{
			"name": "Epicentre",
			"gid": 6861853,
			"iid": 7070869,
			"background": 4,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "20",
			"apply": "Hinder",
			"target": "AoE",
			"description": "You gain $t4 stacks of the Epicentre effect. Each attack you perform will expend a stack and cause a $c5 metre radius area to appear around your target, which lasts $t5 seconds. Enemies inside the area are dealt $d20 physical damage when the area appears and every second afterward. This area also reduces the movement speed of enemies by $t30%. Recharge time does not begin until all stacks of the Epicentre effect have been expended.<br> <br>Each stack of the Upheaval effect increases your Crit Power by $t5% for $t8 seconds.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Brute Force",
	"tier": "2",
	"abilities": [
		{
			"name": "Punishment",
			"gid": 6861854,
			"iid": 7076272,
			"background": 6,
			"cost": 9,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Weaken",
			"apply": "Critical",
			"description": "Whenever you hit a $sWeakened target, you gain a beneficial effect that increase your Critical Power Rating by $c40 per stack for $t10 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Touchdown!",
			"gid": 6838016,
			"iid": 7070873,
			"background": 2,
			"cost": 12,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "12",
			"apply": "Movement,Block",
			"target": "TAoE",
			"description": "Charge: $c15 metre leap to your target. The target must be at least $c3 metres away.<br>You charge your target dealing $d56 physical damage to up to $c6 enemies in a $c5 metre radius as you land and you gain the Minor Block Chance effect, which increases Block Chance by $t15% for $t8 seconds.",
		},
		{
			"name": "Insult to Injury",
			"gid": 6861860,
			"iid": 7076270,
			"background": 6,
			"cost": 16,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical",
			"apply": "Weaken",
			"description": "Whenever you critically hit, your target becomes $sWeakened by a single stack of the Debilitated effect, which reduces all damage dealt by $t3% per stack for $t10 seconds. Debilitated can stack up to $t10 times.",
		},
		{
			"name": "Beatdown",
			"gid": 6838795,
			"iid": 7070872,
			"background": 2,
			"cost": 21,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "45",
			"apply": "Impair",
			"target": "Single",
			"description": "A single target attack that deals $d91 physical damage. If you hit, your target becomes $sImpaired and knocked to the ground for $t3 seconds.",
		},
		{
			"name": "Tenderising",
			"gid": 6861861,
			"iid": 7076273,
			"background": 6,
			"cost": 27,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Weaken",
			"description": "Whenever you hit a $sWeakened target, you perform an additional hit dealing $d7 physical damage.",
		},
		{
			"name": "Full Momentum",
			"gid": 6838807,
			"iid": 7070874,
			"background": 4,
			"cost": 34,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"apply": "Resource",
			"description": "You gain $r5 Hammer Resources and your Momentum is set to $c5 stacks. If you use this ability when you have $c5 stacks of Momentum you get the Never Go Full Momentum effect, increasing your movement speed by $t20% for $t5 seconds. This ability does not trigger and is not affected by global recharge time.",
		},
		{
			"name": "Thunderstruck",
			"gid": 6861862,
			"iid": 7076271,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"react": "Impair,Weaken",
			"description": "Increase the duration of $sImpaired effects you apply by $t35%. Whenever you critically hit a $sWeakened target, you also hit an additional time, dealing $d41 physical damage.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Excessive Damage",
	"tier": "2",
	"abilities": [
		{
			"name": "Ground Pound",
			"gid": 6838810,
			"iid": 7070877,
			"background": 2,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 enemies in a $c5 metre radius around you.<br>Builds $r1 resource for each equipped weapon.<br>A PBAoE attack that deals $d23 physical damage, or $d31 physical damage if you have no Hammer Resources.",
		},
		{
			"name": "Sweetspot",
			"gid": 6861863,
			"iid": 7076274,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical",
			"apply": "Heal",
			"description": "You gain $h30 health each time you critically hit.",
		},
		{
			"name": "No Mercy",
			"gid": 6861201,
			"iid": 7070875,
			"background": 2,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"apply": "Blast",
			"target": "Column",
			"description": "Column: Affects up to $c6 enemies in a $c4 metre wide by $c5 metre long column in front of you.<br>Consumes all Hammer Resources.<br>A column $uBlast attack that deals $d45-94 physical damage, based on the number of resources consumed. Enemies who are killed shortly after being hit will grand you a beneficial effect for $t30 seconds which will cause your next \"No Mercy\" to critically hit.",
		},
		{
			"name": "Improved Blasts",
			"gid": 6861865,
			"iid": 7076275,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Blast",
			"apply": "Weaken",
			"description": "Whenever you hit with a $uBlast ability, your target becomes $sWeakened by a single stack of the Debilitated effect, which reduces all damage dealt by $t3% per stack for $t10 seconds. This effect can stack up to $t10 times.",
		},
		{
			"name": "Piledriver",
			"gid": 6861219,
			"iid": 7070878,
			"background": 2,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"react": "Impair",
			"apply": "Critical",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 enemies in a $c5 metre radius around you.<br>Consumes all Hammer resources.<br>You smash your hammer into the ground, creating a PBAoE that deals $d45-89 physical damage, based on the number of resources consumed. If the attack hits an $sImpaired enemy you receive a single stack of the Critical Rating effect for each Hammer Resource spent. Each stack increases your Critical Rating by $c40 for $t8 seconds. The Critical Rating effect can stack up to $t5 times.",
		},
		{
			"name": "Knuckle Down",
			"gid": 6861866,
			"iid": 7076276,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"apply": "Damage",
			"description": "Increases damage and healing of resource builders by $t10%.",
		},
		{
			"name": "Eruption",
			"gid": 6861218,
			"iid": 7070876,
			"background": 2,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "25",
			"apply": "Impair,Vulnerable",
			"target": "Column",
			"description": "Column: Affects up to $c6 enemies in a $c6 metre wide by $c9 metre area in front of you.<br>You smash your hammer into the ground, creating a column of molten spikes in front of you that deals $d182 physical damage. If you hit, your target becomes $sImpaired and knock the target up in the air for $t3.5 seconds.<br> <br>Applies $sVulnerable to Ranged.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Sledge Factory",
	"tier": "2",
	"abilities": [
		{
			"name": "Grip Whip",
			"gid": 6861220,
			"iid": 7070911,
			"background": 2,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"apply": "Block",
			"target": "Single",
			"description": "Builds $r1 resource for each equipped weapon.<br>A single target attack that deals $d46 physical damage. Grants you a single stack of the Block Rating effect, which increases your Block Rating by $c40 per stack for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "You're Next",
			"gid": 6861867,
			"iid": 7076278,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Block",
			"apply": "Hate,Damage",
			"description": "Whenever you block an attack, you gain a beneficial effect that increases all damage dealt by $t10% and doubles all hate generated for $t6 seconds.",
		},
		{
			"name": "Aftershock",
			"gid": 6861221,
			"iid": 7070910,
			"background": 2,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "4",
			"consume": "-1",
			"apply": "Strike",
			"target": "Single",
			"description": "Consumes all Hammer resources.<br>A single target $uStrike that deals $d76-164 physical damage, based on the number of resources consumed. If the target is still within $c5 metres of you after $t3 seconds, this attack hits a second time dealing $d35 physical damage and you gain the Minor Ward effect, which decreases all damage received by $t7.5% for $t8 seconds",
		},
		{
			"name": "Improved Strikes",
			"gid": 6861868,
			"iid": 7076279,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Strike",
			"description": "Increases the damage and healing of $uStrike abilities by $t10%.",
		},
		{
			"name": "Obsidian Aegis",
			"gid": 6861222,
			"iid": 7070912,
			"background": 2,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"react": "Impair",
			"target": "Single",
			"description": "Consumes all Hammer Resources.<br>A single target attack that deals $d90-178 physical damage, based on the number of resources consumed. If you hit an $sImpaired target, you gain the Major Ward effect, which reduces all damage received by $t25% for $t6 seconds.",
		},
		{
			"name": "Immovable Object",
			"gid": 6861869,
			"iid": 7076277,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"apply": "Block",
			"description": "Whenever an enemy deals damage to you, you deal $d8 physical damage back to your attacker. The amount of damage scales with your maximum health.<br> <br>Also, if you receive $t300 or more damage in a single hit, you have a $t33% chance to gain the Minor Block Chance effect, which increases Block Chance by $t15% for $t8 seconds.",
		},
		{
			"name": "Unstoppable Force",
			"gid": 6861223,
			"iid": 7070913,
			"background": 4,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "30",
			"apply": "Block,Heal",
			"description": "You grow in size by $t25% and gain $h25% more health and deal $t8% more damage for $t8 seconds. You are also healed for $h342. While this buff is active you are immune to all crowd control effects.<br> <br>You also receive the Major Block Chance effect, which increases you Block Chance by $c45% for $t6 seconds.<br> <br>This ability does not trigger and is not affected by global recharge time.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Battering Works",
	"tier": "2",
	"abilities": [
		{
			"name": "Bully",
			"gid": 6861870,
			"iid": 7076281,
			"background": 6,
			"cost": 9,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"react": "Impair",
			"apply": "Resource",
			"description": "Whenever you apply $sImpaired, you Build $r2 Hammer Resources.",
		},
		{
			"name": "Trucker",
			"gid": 6861224,
			"iid": 7070914,
			"background": 2,
			"cost": 12,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "20",
			"apply": "Block,Movement",
			"target": "Single",
			"description": "Charge: $c15 metre charge to the target. The target must be at least $c3 metres away.<br>You charge to the target dealing $d60 damage and you gain the Major Block Chance effect, which increases Block Chance by $c45% for $t6 seconds.",
		},
		{
			"name": "Brick Wall",
			"gid": 6861871,
			"iid": 7076283,
			"background": 6,
			"cost": 16,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Block",
			"apply": "Impair",
			"description": "Whenever you block an attack, your attacker becomes $sImpaired and knocked to the ground for $t2 seconds. This effect has a recharge time of $t30 seconds.",
		},
		{
			"name": "Stone's Throw",
			"gid": 6861225,
			"iid": 7070915,
			"background": 2,
			"cost": 21,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "15",
			"apply": "Hate,Weaken",
			"target": "Single",
			"description": "A single target ranged attack that deals $d114 physical damage. If hit, your target becomes $sWeakened by $t2 stacks of the Debilitated effect, which reduces all damage dealt by $t3% per stack for $t10 seconds. This effect can stack up to $t10 times. Generates a large amount of hate.",
		},
		{
			"name": "No Pain No Gain",
			"gid": 6861899,
			"iid": 7076282,
			"background": 6,
			"cost": 27,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Impair",
			"apply": "Heal",
			"description": "Whenever you hit an $sImpaired target, you heal for $h46.",
		},
		{
			"name": "Furnace",
			"gid": 6861227,
			"iid": 7070916,
			"background": 2,
			"cost": 34,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"apply": "Weaken",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 enemies in a $t5 metre radius around your target.<br>A PBAoE attack that deals $d56 physical damage. Affected targets become $sWeakened by $t5 stacks of the Debilitated effect, which reduces all damage dealt by $t3% per stack for $t10 seconds. This effect can stack up to $t10 times. For each target affected, you gain a single stack of the Protection effect, which increases Physical and Magical Protection by $t35 per stack for $t8 seconds. Protection can stack up to $t5 times.",
		},
		{
			"name": "Forged in Fire",
			"gid": 6861901,
			"iid": 7076280,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"apply": "Heal",
			"description": "Whenever you drop below $t50% health you will regenerate $h40% of your health over $t10 seconds. This effect can apply once every $t40 seconds.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Hammer Pit",
	"tier": "2",
	"abilities": [
		{
			"name": "Razor Shards",
			"gid": 6861230,
			"iid": 7070918,
			"background": 2,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"consume": "-1",
			"apply": "Hate",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 enemies in a $c5 metre radius around you.<br>Consumes all Hammer Resources.<br>A PBAoE attack that deals $d44-88 physical damage based on the number of resources consumed and increases all affected enemies' hate towards you. Grants a hate increasing effect for you next attack. This effect scales based on the amount of resources consumed.",
		},
		{
			"name": "Blindside",
			"gid": 6861909,
			"iid": 7076286,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Block",
			"apply": "Weaken",
			"description": "Whenever you block an attack, you deal $d26 physical damage back to the attacker and cause them to become $sWeakened by a single stack of the Debilitated effect, which reduces all damage dealt by $t3% per stack for $t10 seconds. This effect can stack up to $t10 times.",
		},
		{
			"name": "Rupture",
			"gid": 6861231,
			"iid": 7070919,
			"background": 2,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"apply": "Blast",
			"target": "Column",
			"description": "Column: Affects up to $c6 enemies in a $c4 metre wide by $c5 metre long column in front of you.<br>Builds $r1 resource for each equipped weapon.<br>A column $uBlast attack that deals $d25 physical damage, or $d33 physical damage if you have no Hammer resources.",
		},
		{
			"name": "Bullheaded",
			"gid": 6861910,
			"iid": 7076285,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Blast",
			"description": "Whenever you hit with a $uBlast ability, you gain a single stack of the Protection effect, which increases you Physical and Magical Protection Rating by $c40 per stack for $t8 seconds.",
		},
		{
			"name": "Blowout",
			"gid": 6861232,
			"iid": 7070917,
			"background": 2,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "15",
			"consume": "-1",
			"react": "Weaken",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 enemies in a $c5 metre radius around you, pulsing every second for $t10 seconds.<br>Consumes all Hammer Resources.<br>A pulsing PBAoE attack that deals $d6-12 physical damage per pulse, based on the number of resources consumed. If you hit an $sWeakened target, you gain a stacking effect increasing you health by $h2% for $t10 seconds. This effect stacks a maximum of $t5 times.",
		},
		{
			"name": "Faultline",
			"gid": 6861930,
			"iid": 7076284,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Blowout",
			"description": "Increase the duration of \"Blowout\" by $t5 seconds. Reduces the recharge time of \"Blowout\" by $t5 seconds.",
		},
		{
			"name": "Raging Volcano",
			"gid": 6861233,
			"iid": 7070920,
			"background": 2,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cast": "6",
			"cooldown": "30",
			"apply": "Block",
			"target": "PBAoE",
			"description": "Channelled: Every second for $t6 seconds.<br>PBAoE: Affects up to $c6 enemies in a $c5 metre radius around you.<br>A channelled PBAoE attack that causes enemies within $c10 metres to attack you and deal $d100 physical damage per hit to enemies withing $c5 metres. The last hit will deal $d199 physical damage.<br> <br>While channelling this ability, you have a Block Chance of $t100% and your movement speed is increased by $t30%. <br> <br>Each time this ability hits a target, you gain $t1 stack of the Raging Volcano effect. This effect can stack up to $t6 times and lasts $t8 seconds and will cause your abilities to deal an additional $d29 physical damage.",
		},
	]
});
