// Auxillary Weapons
index = 0;

TSW.Wheel[index].cells.push({
	"name": "Whip",
	"tier": "1",
	"abilities": [
		{
			"name": "Crack!",
			"gid": 8102554,
			"iid": 8148113,
			"background": 2,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cooldown": "15",
			"target": "Column",
			"description": "Column: Affects up to $c6 enemies in a $c3 metre wide by $c5 metre long area in front of you.<br>A column attack that deals $d150 physical damage.",
		},
		{
			"name": "Jones in the Fast Lane",
			"gid": 8102575,
			"iid": 8148117,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Reduces the recharge time of Whip abilities by $t50%.",
		},
		{
			"name": "Whip it Good",
			"gid": 8102556,
			"iid": 8148120,
			"background": 2,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "2",
			"cooldown": "25",
			"target": "Cone",
			"description": "Channelled: Every $c0.4 seconds for $c2 seconds.<br>Cone: Affects up to $c6 enemies in a $c5 metre long $c120 degree cone in front of you.<br>A Channelled attack that deals $d39 physical damage per hit.",
		},
		{
			"name": "Sonic Boom",
			"gid": 8102585,
			"iid": 8148116,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Whenever you hit a target with a Whip ability, you perform an additional hit on the target and up to $c4 enemies within $c3 metres around it that deals $d9 physical damage.<br>Activating \"Giddy Up\" causes the above effect to be triggered around you.",
		},
		{
			"name": "Giddy Up",
			"gid": 8102558,
			"iid": 8148119,
			"background": 4,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "0.5",
			"cooldown": "30",
			"target": "PBAoE",
			"description": "PBAoE: Affects you and up to $c4 friends in a $c10 metre radius around you.<br>A PBAoE that gives affected targets a beneficial effect, which increases their movement speed by $t15% for $t6 seconds.",
		},
		{
			"name": "Whiplash",
			"gid": 8102604,
			"iid": 8148114,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Whenever you hit a target with a Whip ability, you apply a detrimental effect which reduces the Physical and Magical Protection of the target by $t200 for $t7 seconds.<br>Activating \"Giddy Up\" also applies the detrimental effect to $c5 enemies around you.",
		},
		{
			"name": "Whippersnapper",
			"gid": 8102560,
			"iid": 8148118,
			"background": 2,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cooldown": "45",
			"target": "Column",
			"description": "Column: Affects the nearest enemy in a $c3 metre wide by $c5 metre long area in front of you.<br>A column attack that deals $d202 physical damage to the nearest enemy. Pulls the target towards you.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Chainsaw",
	"tier": "1",
	"abilities": [
		{
			"name": "Timber",
			"gid": 7953242,
			"iid": 7959508,
			"background": 2,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cooldown": "15",
			"target": "Single",
			"description": "A single target attack that deals $d224 physical damage.",
		},
		{
			"name": "Revved Up",
			"gid": 7953647,
			"iid": 7959504,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Increases the damage dealt by \"Rotting Teeth\" by $t100%.",
		},
		{
			"name": "Hurly-Burly",
			"gid": 7953243,
			"iid": 7959507,
			"background": 2,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "2.5",
			"cooldown": "30",
			"target": "PBAoE",
			"description": "Channelled: Every $c0.5 seconds for $c2.5 seconds.<br>PBAoE: Affects up to $c6 enemies in a $c5 metre radius around you.<br>A channelled PBAoE attack that deals $d44 physical damage.",
		},
		{
			"name": "No Love Lost",
			"gid": 7953648,
			"iid": 7959510,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Improves \"Rotting Teeth\" to generate $t263 more hate each time it deals damage.",
		},
		{
			"name": "Diamond Grit",
			"gid": 7953288,
			"iid": 7959506,
			"background": 4,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cooldown": "30",
			"apply": "Barrier",
			"description": "Places a reflect barrier on you that reflects $h50% of incoming damage back to the attacker and dissipates after reflecting $h493 damage or after $t10 seconds. The magnitude of the barrier scales based on the Weapon Power of your Chainsaw.",
		},
		{
			"name": "Degradation",
			"gid": 7953649,
			"iid": 7959509,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Increases the heal required to remove \"Rotting Teeth\" by $t650.",
		},
		{
			"name": "The Carver's Art",
			"gid": 7953316,
			"iid": 7959505,
			"background": 2,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "3",
			"cooldown": "90",
			"target": "Single",
			"description": "Channelled: Every $c0.2 seconds for $c3 seconds.<br>A channelled attack that deals $d12 physical damage per hit. Both you and the target are unable to move while this ability is active.",
		},
	]
});


TSW.Wheel[index].cells.push({
	"name": "Quantum",
	"tier": "1",
	"abilities": [
		{
			"name": "Vector-Space",
			"gid": 7988763,
			"iid": 7999237,
			"background": 5,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "0.5",
			"cooldown": "15",
			"apply": "Afflict",
			"target": "Single",
			"description": "Vector:<br>A single target attack that deals $d57 magical damage and also applies a damage over time effect that deals $d12 magical damage every second for $t6 seconds.<br>Becomes \"Space\" after a successful hit.<br> <br>Space:<br>If the target does not have the \"Vector\" damage over time effect, this is a single target attack that deals $d150 magical damage.<br>If the target has the \"Vector\" damage over time effect, this attack instead affects up to $c6 enemies in a $c5 metre radius around the target, dealing $d150 magical damage.<br>Becomes \"Vector\" after a successful activation or $t5 seconds have passed.",
		},
		{
			"name": "Supersymmetry",
			"gid": 7989057,
			"iid": 7999227,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Whenever you hit a target that has $t50% or more of their maximum health remaining with a Quantum ability, you will perform an additional hit that deals $d24 magical damage.",
		},
		{
			"name": "Collider-Collapse",
			"gid": 7989102,
			"iid": 7999235,
			"background": 5,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "2.5",
			"cooldown": "30",
			"target": "Single",
			"description": "Collider:<br>A channelled attack against the closest target in a straight line in front of you that deals $d36 magical damage per hit every $t0.25 seconds for $t2.5 seconds. Each time you hit you gain a single stack of \"Collider\" counters.<br>becomes \"Collapse\" if you have gained at least one \"Collider\" counter by the end of the channel.<br> <br>Collapse:<br>A single target attack that deals $d32 magical damage for each \"Collider\" counter you have up to a maximum of $d320 magical damage.<br>Becomes \"Collider\" after a successful activation or $t5 seconds have passed.",
		},
		{
			"name": "Energy Transfer",
			"gid": 7989132,
			"iid": 7999230,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Increases the effectiveness of \"Space\", \"Collapse\", \"Density\", and \"Oblivion\" by $t25%<br> <br>Reduces the effectiveness of \"Vector\", \"Collider\", \"Charge\", and \"Polestar\" by $t20%.",
		},
		{
			"name": "Charge-Density",
			"gid": 7989133,
			"iid": 7999233,
			"background": 3,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cooldown": "30",
			"apply": "HoT",
			"target": "Single",
			"description": "Charge:<br>Gives a friend a heal over time effect that heals for $h35 every second for $t6 seconds.<br>Becomes \"Density\" after a successful activation.<br> <br>Density:<br>A heal that affects up to $c6 friends in a $5 metre radius around the target, healing for $h125. if the defensive target has your \"Charge\" heal over time effect, you also leave a $c5 metre radius persistent ground area around the target for $t5 seconds. Every second up to $c5 friends in the area are healed for $h6. <br>Becomes \"Charge\" after a successful activation or $t5 seconds have passed.",
		},
		{
			"name": "Probability Rules",
			"gid": 7990187,
			"iid": 7999229,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Whenever you activate a Quantum ability, there is a $t20% chance that its recharge does not trigger.",
		},
		{
			"name": "Polestar-Oblivion",
			"gid": 7989140,
			"iid": 7999226,
			"background": 5,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "0.5",
			"cooldown": "45",
			"apply": "Impair",
			"target": "TAoE",
			"description": "Polestar:<br>An attack that affects up to $c2 enemies in a $c1 metre radius around the targeted point, dealing $d104 magical damage. Affected targets also receive the \"Polestar\" effect for $t5 seconds.<br>Becomes \"Oblivion\" after a successful hit.<br> <br>Oblivion:<br>A cone attack that affects up to $c6 enemies in a $c7 metre long $c120 degree cone in front of you, dealing $d143 magical damage. Affected targets that have the \"Polestar\" effect become $sImpaired and unable to act for $t2 seconds.<br>Becomes \"Polestar\" after a successful activation or $t5 seconds have passed.",
		},
	]
});



TSW.Wheel[index].cells.push({
	"name": "Flamethrower",
	"tier": "1",
	"abilities": [
		{
			"name": "Dragon's Breath",
			"gid": 8156718,
			"iid": 8227072,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "2",
			"cooldown": "15",
			"target": "Cone",
			"description": "Channelled: Every $c0.4 seconds for $c2 seconds.<br>Cone: Affects up to $c6 enemies in a $c15 metre long $c60 degree cone in front of you.<br>A channelled cone attack that deals $d39 physical damage per hit.",
		},
		{
			"name": "Searing Magnesium",
			"gid": 8156801,
			"iid": 8227067,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Increases damage dealt by Flamethrower abilities by $t15%.",
		},
		{
			"name": "Scorched Earth",
			"gid": 8156727,
			"iid": 8227068,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "0.5",
			"cooldown": "25",
			"target": "GTAoE",
			"description": "Creates a wall of fire which extends $c2 metres forward and $c4 metres to either side of the targeted location and lasts $t6 seconds. Every $t0.3 seconds it will hit up to $t5 enemies in the area dealing $d19 physical damage.",
		},
		{
			"name": "Assiduous Burn",
			"gid": 8156802,
			"iid": 8227065,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Increases the duration of \"Incendiary Expertise\" to $t10 seconds. Also, whenever \"Incendiary Expertise\" deals damage, all Flamethrower ability cooldowns are reduced by $t5% of their remaining cooldown time.",
		},
		{
			"name": "Smells Like Victory-Fire It Up",
			"gid": 8156730,
			"iid": 8227070,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "0.5",
			"cooldown": "30",
			"target": "GTAoE",
			"description": "Smells Like Victory:<br>An attack that affects up to $c6 enemies in a $c5 metre radius around the targeted point, dealing $d15 physical damage. Affected targets also receive the \"smells Like Victory\" effect for $t3 seconds, increasing damage taken by $t2%. <br>Becomes \"Fire It Up\" after a successful hit.<br> <br>Fire It Up:<br>An attack that deals $d112 physical damage. if the affected target has the \"Smells Like Victory\" effect, the attack instead deals $d224 physical damage.<br>Becomes \"Smells Like Victory\" after a successful activation or $t5 seconds have passed.",
		},
		{
			"name": "Viscous Accelerant",
			"gid": 8156804,
			"iid": 8227063,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Whenever you hit with a Flamethrower ability, the target has its movement speed reduced by $t20% for $t6 seconds.",
		},
		{
			"name": "Cremate",
			"gid": 8156794,
			"iid": 8227071,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "1",
			"cooldown": "60",
			"apply": "Afflict",
			"target": "Single",
			"description": "A single target attack that deals $d7 physical damage and $d21 physical damage every second for $t10 seconds. The target also becomes rooted to the ground for $t2 seconds.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Rocket Launcher",
	"tier": "1",
	"abilities": [
		{
			"name": "Pop Shot",
			"gid": 7760057,
			"iid": 7896585,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "1",
			"cooldown": "15",
			"target": "TAoE",
			"description": "TAoE: Affect up to $c6 enemies in a $c5 metre radius around your target.<br>A TAoE attack that deals $d150 physical damage.",
		},
		{
			"name": "Rangefinder",
			"gid": 7760065,
			"iid": 7896580,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Increases the attack range of all Rocket Launcher abilities by $t5 metres.",
		},
		{
			"name": "Clusterstruck",
			"gid": 7760118,
			"iid": 7896584,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "1.5",
			"cooldown": "30",
			"target": "GTAoE",
			"description": "GTAoE: Affects up to $c6 enemies in a $c5 metre radius around the targeted point.<br>A GTAoE attack that deals $d173 physical damage.",
		},
		{
			"name": "Rocket Science",
			"gid": 7760093,
			"iid": 7896579,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Reduces the recharge time of Rocket Launcher abilities by $t50%.",
		},
		{
			"name": "Death From Above",
			"gid": 7760095,
			"iid": 7896583,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cooldown": "40",
			"description": "You rocket jump $c15 metres forward hitting up to $c6 enemies in a $c5 metre radius where you take off and where you land, dealing $d99 physical damage. Deals $d9% of your maximum health as damage to you when activated.",
		},
		{
			"name": "Warhead",
			"gid": 7760116,
			"iid": 7896577,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"auxillary": true,
			"description": "Increases damage dealt by Rocket Launcher abilities by $t15%.",
		},
		{
			"name": "Big Red Button",
			"gid": 7760068,
			"iid": 7896581,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"auxillary": true,
			"cast": "2",
			"cooldown": "90",
			"target": "TAoE",
			"description": "TAoE: Affects up to $c6 enemies in a $c5 metre radius around your target.<br>A TAoE attack that deals $d196 physical damage.",
		},
	]
});

// Misc

TSW.Wheel[index].cells.push({
	"name": "Survivalism <span style=\"font-style:italic;\">(Healing)</span>",
	"ui_name": "Survivalism",
	"tier": "1",
	"abilities": [
		{
			"name": "Sleight of Hand",
			"gid": 7494887,
			"iid": 7653201,
			"background": 4,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "25",
			"description": "Removes all active crowd control effects from you and makes you immune to further crowd control effects for $t7 seconds. This ability does not trigger global recharge time.",
		},
		{
			"name": "Unfair Advantage",
			"gid": 7494904,
			"iid": 7653216,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"react": "Heal",
			"description": "Increases the effectiveness of healing received by $t5%.",
		},
		{
			"name": "Turn the Tables",
			"gid": 7494903,
			"iid": 7653203,
			"background": 3,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "35",
			"apply": "Heal",
			"description": "A self heal that heals for $h642. This value is not affected by your healing power or any other heal increasing effects.",
		},
		{
			"name": "Cannonball",
			"gid": 7494902,
			"iid": 7653214,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"description": "Whenever you activate a movement ability, you also gain the Minor Ward effect, which reduces all damage received by $t7.5% for $t8 seconds.",
		},
		{
			"name": "Speed Freak",
			"gid": 7494901,
			"iid": 7653202,
			"background": 4,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"description": "Increases your movement speed by $t25% for $t6 seconds. Cleanses $sHindered and prevents you from being $sHindered for the duration.",
		},
		{
			"name": "Tenacity",
			"gid": 7494900,
			"iid": 7653215,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"apply": "HoT",
			"description": "Whenever you become $sImpaired or $sHindered, you gain a heal over time effect that heals you for $h25 every second for $t5 seconds.",
		},
		{
			"name": "Last Resort",
			"gid": 7494899,
			"iid": 7653200,
			"background": 4,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "45",
			"apply": "Heal",
			"description": "You become unable to act for $t8 seconds. During this period you are invulnerable and are healed for $h200 every second. This value is not affected by your healing power or any other heal increasing effects.<br> <br>You also gain the Minor Ward effect, which reduces all damage received by $t7.5% for $t8 seconds when the invulnerability effect ends.<br> <br>This ability does not trigger and is not affected by global recharge time.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Subversion <span style=\"font-style:italic;\">(DPS)</span>",
	"ui_name": "Subversion",
	"tier": "1",
	"abilities": [
		{
			"name": "Confuse",
			"gid": 7494898,
			"iid": 7653204,
			"background": 4,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"description": "Reduces the amount of hate the target has towards you, making it more likely to attack others instead of you. The target's hate towards you is reduced by $t50%.",
		},
		{
			"name": "Subtlety",
			"gid": 7494897,
			"iid": 7653218,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"description": "Reduces the amount of hate enemies will gain towards you, making them more likely to attack others instead of you. Enemies will gain hate towards you at a $t75% rate.",
		},
		{
			"name": "Mass Confusion",
			"gid": 7494896,
			"iid": 7653206,
			"background": 4,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"description": "TAoE: Affects up to $c6 enemies in a $c5 metre radius around the target.<br>A TAoE detaunt that reduces the amount of hate affected targets have towards you, making them more likely to attack others instead of you. The targets' hate towards you is reduces by $t33%.",
		},
		{
			"name": "Under the Radar",
			"gid": 7494895,
			"iid": 7653219,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"react": "Critical,Penetrate",
			"description": "Whenever you critically hit or penetrate, you also make the target more likely to attack others instead of you by reducing its hate towards you by $t400.",
		},
		{
			"name": "Misdirection",
			"gid": 7494894,
			"iid": 7653207,
			"background": 4,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"description": "For the next $t8 seconds, $t50% of the hate enemies gain towards you is instead transferred as hate towards your defensive target.",
		},
		{
			"name": "Kill Streak",
			"gid": 7494893,
			"iid": 7653217,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"description": "Whenever you or a member of your group kills an enemy, you gain $t1 stack of a beneficial effect that increases the damage you deal by $t3% per stack for $t10 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Do or Die",
			"gid": 7494892,
			"iid": 7653205,
			"background": 4,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "45",
			"description": "Increases the direct damage you deal by $t25% for $t10 seconds. This ability does not trigger and is not affected by global recharge time.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Turbulence <span style=\"font-style:italic;\">(Tanking)</span>",
	"ui_name": "Turbulence",
	"tier": "1",
	"abilities": [
		{
			"name": "Provoke",
			"gid": 7494891,
			"iid": 7653210,
			"background": 4,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "40",
			"apply": "Hate",
			"description": "Taunts the target, causing it to gain enough hate towards you to start attacking you and forcing the target to attack you for $t3 seconds.",
		},
		{
			"name": "Agitator",
			"gid": 7494890,
			"iid": 7653220,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"apply": "Hate",
			"description": "Increases the amount of hate enemies will gain towards you, making them more likely to attack you instead of others. Enemies will gain hate towards you at a $t350% rate.",
		},
		{
			"name": "Mass Provocation",
			"gid": 7494889,
			"iid": 7653208,
			"background": 4,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "50",
			"description": "TAoE: Affects up to $c6 enemies in a $c5 metre radius around the target.<br>A TAoE taunt that forces affected targets to attack you for $t5 seconds.",
		},
		{
			"name": "Fuel to the Fire",
			"gid": 7494888,
			"iid": 7653221,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"apply": "Hate",
			"description": "Whenever you hit, the target generates $t200 extra hate towards you.",
		},
		{
			"name": "Mockingbird",
			"gid": 7494907,
			"iid": 7653209,
			"background": 3,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "20",
			"apply": "Heal,Hate",
			"description": "You gain a beneficial effect, which causes all hits against you during the next $t10 seconds to also heal you for $h9 and cause attackers to gain $t200 extra hate towards you.",
		},
		{
			"name": "Resilient Defender",
			"gid": 7494906,
			"iid": 7653222,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"react": "Defense,Block,Evade",
			"apply": "Heal",
			"description": "Whenever you evade or block or an attack glances, you are healed for $h15.",
		},
		{
			"name": "Stoicism",
			"gid": 7494961,
			"iid": 7653211,
			"background": 4,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "30",
			"apply": "Hate",
			"description": "You gain a beneficial effect that reduces the damage you take by $t20% and causes enemies to gain hate against you at a $t500% rate for $t10 seconds. This abliity does not trigger and is not affected by global recharge time.",
		},
	]
});
