// Pistols
index = 8;

TSW.Wheel[index].cells.push({
	"name": "Armed",
	"tier": "1",
	"abilities": [
		{
			"name": "The Business",
			"gid": 6450943,
			"iid": 6814174,
			"background": 1,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"build": "1",
			"target": "Single",
			"description": "Builds 1 resource for each equipped weapon.<br>A single target attack that hits $t3 times, dealing $d16 physical damage per hit.",
		},
		{
			"name": "Magnum",
			"gid": 6454296,
			"iid": 6814215,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "The Business",
			"apply": "Weaken",
			"description": "\"The Business\" also causes the target to become $sWeakened by a single stack of the Corrupted effect, which reduces the effectiveness of heal, barrier and leech effects by $t5% per stack for $t10 seconds. This effect can stack up to $t10 times.",
		},
		{
			"name": "Shootout",
			"gid": 6453670,
			"iid": 6814178,
			"background": 1,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "2.5",
			"cooldown": "4",
			"consume": "-1",
			"apply": "Focus",
			"target": "Single",
			"description": "Channelled: Every $t0.5 seconds for $t2.5 seconds.<br>Consumes all Pistol Resources.<br>A channelled $uFocus attack that deals $d41-61 physical damage per hit, based on the number of resources consumed.",
		},
		{
			"name": "Coup de Grace",
			"gid": 6454217,
			"iid": 6814214,
			"background": 6,
			"cost": 2,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"apply": "Heal",
			"description": "Whenever an enemy dies with your Pistol resources remaining, up to $c5 friends in a $c5 metre radius around that enemy are healed by $h51.",
		},
		{
			"name": "Drone Kit",
			"gid": 6452208,
			"iid": 6814172,
			"background": 1,
			"cost": 3,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "4",
			"consume": "-1",
			"target": "AoE",
			"description": "Consumes all Pistol resources.<br>Summons a drone that will follow you around for $t20 seconds. Every $t2 seconds it will fire at the closet enemy within $c5 metres and deal $d11-22 physical damage, based on the number of resources consumed.",
		},
		{
			"name": "Straight Shooter",
			"gid": 6454297,
			"iid": 6814216,
			"background": 6,
			"cost": 4,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"apply": "Damage",
			"description": "Increases damage dealt by Pistol abilities by $t10%.",
		},
		{
			"name": "Dirty Tricks",
			"gid": 6454141,
			"iid": 6814173,
			"background": 1,
			"cost": 7,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "25",
			"react": "Anima Deviation",
			"apply": "Hinder,Weaken",
			"target": "GTAoE",
			"description": "GTAoE: Affects up to $c6 enemies in a $c5 metre radius around the targeted point.<br>A GTAoE attack that deals $d345 physical damage.<br> <br>Affected targets also become $sHindered and rooted to the ground for $t4 seconds. Targets also become $sWeakened by $c5 stacks of the Corrupted effect, which reduces the effectiveness of heal, barrier and leech effects by $c5% per stack for $t10 seconds. This effect can stack up to $c10 times.<br> <br>Susceptible to $sAnima Deviation.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Dangerous",
	"tier": "1",
	"abilities": [
		{
			"name": "Hothead",
			"gid": 6454198,
			"iid": 6814218,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Hinder",
			"apply": "Critical",
			"description": "Whenever you apply $sHindered you gain the Minor Critical Chance effect, which increase your Critical Chance by $t10% for $t8 seconds.",
		},
		{
			"name": "Above the Law",
			"gid": 6560768,
			"iid": 6814176,
			"background": 1,
			"cost": 1,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "15",
			"build": "1",
			"react": "Hinder",
			"target": "GTAoE",
			"description": "GTAoE: Places an area of effect that affects up to $c6 enemies in a $c5 metre radius around the targeted point every second for $t10 seconds.<br>Builds $r2 resource for each equipped weapon on each target in the area placed.<br>A persistent GTAoE attack that creates an area on the ground that deals $d7 physical damage, or $d8 physical damage to targets that are $sHindered.",
		},
		{
			"name": "Vigilante",
			"gid": 6560782,
			"iid": 6814220,
			"background": 6,
			"cost": 1,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Above the Law",
			"description": "Increases the damage of \"Above the Law\" by $t10% and the duration by $t5 seconds.",
		},
		{
			"name": "Deadly Aim",
			"gid": 6452081,
			"iid": 6814177,
			"background": 4,
			"cost": 2,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "90",
			"apply": "Critical",
			"description": "Gives all group members a beneficial effect that increases Critical Chance by $t40% for $t10 seconds. Affected group members also gain the \"Uncalibrated\" effect which prevents them from gaining the \"Deadly Aim\" effect for $t90 seconds.",
		},
		{
			"name": "Calling the Shots",
			"gid": 6452082,
			"iid": 6814217,
			"background": 6,
			"cost": 3,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Deadly Aim",
			"description": "Reduces the recharge time of \"Deadly Aim\" by $t30 seconds and reduces the duration of the \"Uncalibrated\" effect for $t30 seconds.",
		},
		{
			"name": "Wanted",
			"gid": 6451042,
			"iid": 6814175,
			"background": 1,
			"cost": 4,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "4",
			"consume": "-1",
			"apply": "Chain",
			"target": "Chain",
			"description": "Chain: Jumps up to $c5 metres $c5 times, hitting up to $c6 enemies.<br>Consumes all Pistol resources.<br>A $uChain attack that deals $d45-89 physical damage, based on the number of resources consumed.",
		},
		{
			"name": "Rapid Getaway",
			"gid": 6454304,
			"iid": 6814219,
			"background": 6,
			"cost": 7,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"apply": "Critical",
			"description": "Whenever you activate any resource consumer you gain a beneficial effect that increases your movement speed by $t15% for $t5 seconds and you gain the Minor Critical Chance effect, which increases your Critical Chance by $t10% for $t8 seconds.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Bullet Hell",
	"tier": "2",
	"abilities": [
		{
			"name": "Hair Trigger",
			"gid": 6942465,
			"iid": 7519391,
			"background": 1,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"build": "1",
			"apply": "Focus",
			"target": "Single",
			"description": "Channelled every $t0.25 seconds for $t1 seconds.<br>Builds $r1 Resource for each equipped weapon.<br>A channelled $uFocus attack dealing $d12 physical damage per hit.",
		},
		{
			"name": "Increased Focus",
			"gid": 6942466,
			"iid": 7519432,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Focus",
			"apply": "Critical",
			"description": "$uFocus attacks have a $t7.5% increased chance to critically hit.",
		},
		{
			"name": "Start & Finish",
			"gid": 6942467,
			"iid": 7519389,
			"background": 1,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"cooldown": "4",
			"consume": "-1",
			"react": "Weaken",
			"target": "Single",
			"description": "Consumes all Pistol resources.<br>A single target attack that performs $t2 hits. The first hit deals $d23 physical damage. The second hit deals $d63-144 physical damage or $d69-151 physical damage if the target is $sWeakened.",
		},
		{
			"name": "Mad Skills",
			"gid": 6942468,
			"iid": 7519430,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical",
			"apply": "Critical",
			"description": "Whenever you critically hit, you gain a single stack of the Critical Rating effect, which increases your Critical Rating by $c40 per stack for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Big Forty Five",
			"gid": 6942469,
			"iid": 7519393,
			"background": 1,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1.5",
			"cooldown": "4",
			"consume": "-1",
			"target": "Single",
			"description": "Consumes all Pistol resources.<br>A single target attack dealing $d131-227 physical damage, based on the number of resources consumed.",
		},
		{
			"name": "Quick Forty Five",
			"gid": 6942470,
			"iid": 7519428,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Big Forty Five",
			"description": "Reduces the activation time of \"Big Forty Five\" by $t0.5 seconds.",
		},
		{
			"name": "Gun Crazy",
			"gid": 6942472,
			"iid": 7519395,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cast": "3",
			"cooldown": "20",
			"apply": "Vulnerable",
			"target": "Single",
			"description": "Channelled: Every $t0.3 seconds for $t3 seconds.<br>•First $c3 hits: $d21 physical damage.<br> <br>•Next $c3 hits: $d35 physical damage.<br> <br>•Next $c3 hits: $d61 physcial damage in a $c5 metre area around the target.<br> <br>•Final hit: $d173 physical damage.<br> <br>Applies $sVulnerable to Magic.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Crossfire",
	"tier": "2",
	"abilities": [
		{
			"name": "Bad Break",
			"gid": 6942473,
			"iid": 7519427,
			"background": 6,
			"cost": 9,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Hinder",
			"apply": "Weaken",
			"description": "Whenever you hit a $sHindered target, the target also becomes $sWeakened by $t2 stacks of the Corrupted effect, which reduces the effectiveness of heal, barrier and leech effects by $t5% per stack for $t10 seconds. This effect can stack up to $t10 times.",
		},
		{
			"name": "Shake and Bake",
			"gid": 6942474,
			"iid": 7519384,
			"background": 1,
			"cost": 12,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "45",
			"apply": "Hinder,Movement",
			"target": "Column",
			"description": "Column Dash: Dash forward $c10 metres, affecting up to $c6 enemies in a $c6 metre wide column along the way.<br>A column dash attack that deals $d60 physical damage. Affected targets also become $sHindered and unable to move for $t4 seconds.",
		},
		{
			"name": "Fear and Wonder",
			"gid": 6942475,
			"iid": 7519425,
			"background": 6,
			"cost": 16,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical",
			"apply": "Weaken",
			"description": "Whenever you critically hit, the target also becomes $sWeakened by $t2 stacks of the Corrupted effect, which reduces the effectiveness of heal, barrier and leech effects by $t5% per stack for $t10 seconds. This effect can stack up to $t10 times.",
		},
		{
			"name": "Gun-Fu",
			"gid": 6942476,
			"iid": 7519387,
			"background": 4,
			"cost": 21,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cooldown": "30",
			"apply": "Resource",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $t6 enemies within a $t5 metre radius around you.<br>Applies $t5 Pistol Resources to each target. Reduces the recharge time of all Pistol resource consumers currently recharging by $t4 seconds.",
		},
		{
			"name": "One in the Chamber",
			"gid": 6942477,
			"iid": 7519423,
			"background": 6,
			"cost": 27,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical",
			"description": "Whenever you critical hit, you also perform an additional hit dealing $d28 physical damage to the target.",
		},
		{
			"name": "Marked",
			"gid": 6942478,
			"iid": 7519386,
			"background": 1,
			"cost": 34,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1.5",
			"cooldown": "30",
			"apply": "Weaken",
			"target": "Single",
			"description": "A single target attack deals $d163 physical damage. The target also becomes $sWeakened by $t5 stacks of the Corrupted effect, which reduces the effectiveness of heal, barrier and leech effects by $t5% per stack for $t10 seconds. This effect can stack up to $t10 times.",
		},
		{
			"name": "Seal the Deal",
			"gid": 6942479,
			"iid": 7519422,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"apply": "Damage",
			"description": "Increases the damage and healing done by resource consuming abilities by $t20% and also increases the critical and penetration chance of these abilities by $t5%.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Last One Standing",
	"tier": "2",
	"abilities": [
		{
			"name": "Killer Flow",
			"gid": 6942480,
			"iid": 7519381,
			"background": 1,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"build": "1",
			"target": "PBAoE",
			"description": "PBAoE: Affects up to $c6 targets in a $c5 metre radius around you.<br>Builds $r1 resource for each equipped weapon.<br>A PBAoE attack that deals $d24 physical damage.",
		},
		{
			"name": "Running Circles",
			"gid": 6942481,
			"iid": 7519417,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical",
			"description": "Whenever you critically hit, you gain a beneficial effect that increases your movement speed by $t10% for $t5 seconds. Whenever you hit a target when you are moving, you will also perform an additional hit dealing $d6 physical damage to the target.",
		},
		{
			"name": "Semi-Auto",
			"gid": 6942482,
			"iid": 7519380,
			"background": 1,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "2",
			"cooldown": "4",
			"consume": "-1",
			"apply": "Chain",
			"target": "Chain",
			"description": "Channelled: Every $t0.4 seconds for $t2 seconds.<br>Chain: Jumps up to $c5 metres $c5 times, hitting up to $c6 enemies.<br>Consumes all Pistol Resources.<br>A channelled $uChain attack that deals $d17-26 physical damage per hit, based on the number of resources consumed.",
		},
		{
			"name": "Chain Misery",
			"gid": 6942483,
			"iid": 7519420,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Chain",
			"apply": "Weaken",
			"description": "Whenever you hit with a $uChain attack, the target also becomes $sWeakened by $t1 stack of the Corrupted effect, which reduces the power of all outgoing heal, barrier and leech effects by $t5% per stack for $t10 seconds. This effect can stack up to $t10 times.",
		},
		{
			"name": "Set 'Em Up",
			"gid": 6942484,
			"iid": 7519378,
			"background": 1,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"cooldown": "4",
			"consume": "-1",
			"react": "Hinder",
			"apply": "Resource",
			"target": "TAoE",
			"description": "TAoE: Affects up to $c6 enemies in a $c5 metre radius around the target.<br>Consumes all Pistol resources.<br>A TAoE attack that deals $d46-91 physical damage, based on the number of resources consumed. If any affected target is $sHindered you gain $c2 resources for your secondary weapon.",
		},
		{
			"name": "Closer",
			"gid": 6942485,
			"iid": 7519418,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"apply": "Damage",
			"description": "Increases the damage and healing done by resource consuming abilities by $t10%.",
		},
		{
			"name": "Bullet Ballet",
			"gid": 6942486,
			"iid": 7519382,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cast": "2",
			"cooldown": "20",
			"apply": "Critical,Vulnerable",
			"target": "PBAoE",
			"description": "Channelled: Every $t0.2 seconds for $t2 seconds.<br>PBAoE: Affects $c6 enemies in a $c5 metre radius around you.<br>A channelled PBAoE attack that deals $d43 physical damage. Damage is increased to $d21-109 physical damage to targets based on the number of Pistol Resources you have applied to each target.<br> <br>Also, whenever you hit, you gain a single stack of the Critical Rating effect, which increases your Critical Rating by $c40 per stack for $t8 seconds. This effect can stack up to $t5 times.<br> <br>While channelling you are rooted to the ground.<br> <br>Applies $sVulnerable to Melee.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Troubleshooting",
	"tier": "2",
	"abilities": [
		{
			"name": "Collaboration",
			"gid": 6942487,
			"iid": 7519373,
			"background": 1,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"build": "1",
			"apply": "Cleanse",
			"target": "Single",
			"description": "Builds $r1 resource for each equipped weapon.<br>A single target attack that deals $d46 physical damage. Cleanses you of $t1 detrimental effect. This effect has an internal recharge time of $t5 seconds.",
		},
		{
			"name": "Ready for More",
			"gid": 6942489,
			"iid": 7519413,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Focus",
			"apply": "Cleanse",
			"description": "Whenever you finish channelling a $uFocus ability, you also perform a PBAoE that removes $t1 detrimental effect from up to $t3 friends around you. This cannot happen more than once every $t10 seconds.",
		},
		{
			"name": "Bond, Strong Bond",
			"gid": 6942490,
			"iid": 7519374,
			"background": 1,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "3",
			"cooldown": "4",
			"consume": "-1",
			"apply": "Cleanse",
			"target": "Single",
			"description": "Channelled: Every $t0.3 seconds for $t3 seconds.<br>Consumes all Pistol resources.<br>A channelled attack that deals $d18-29 physical damage, based on the number of resources consumed. At the end of the channel, cleanses $t1 detrimental effect from up to $c5 allies within $c5 metres of you.",
		},
		{
			"name": "Critical Help",
			"gid": 6942491,
			"iid": 7519415,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"apply": "Critical",
			"description": "Whenever you summon a manifestation, turret, mine or drone, you also gain $t1 stack of the Critical Rating effect, which increases Critical Rating by $c40 per stack for $t8 seconds. This effect can stack up to $t5 times.",
		},
		{
			"name": "Area Drone",
			"gid": 6942492,
			"iid": 7519376,
			"background": 1,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"cooldown": "4",
			"consume": "-1",
			"react": "Weaken",
			"target": "AoE",
			"description": "Consumes all Pistol Resources.<br>Summons a drone that will follow the target around for $t5 seconds. Every second it will attack up to $c6 enemies around the target, dealing $d15-30 physical damage, or $d18-35 physical damage to targets that are $sWeakened. If the target dies before the drone is finished attacking it will deal $d38-76 physical damage to targets within the same area. Damage scales based on the number of resources consumed.",
		},
		{
			"name": "Shot in the Arm",
			"gid": 6942493,
			"iid": 7519411,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Cleanse",
			"apply": "Heal",
			"description": "Whenever you attempt to cleanse a detrimental effect, the target is also healed for $h15 and the recharge time of all movement abilities currently recharging is reduced by $c1 second.",
		},
		{
			"name": "Pistol Love",
			"gid": 6942498,
			"iid": 7519372,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cast": "1",
			"cooldown": "25",
			"apply": "Cleanse",
			"target": "Single",
			"description": "Cleanses the defensive target of all detrimental effects.<br> <br>After cleansing, the target cannot be $sWeakened, $sHindered or $sImpaired for $t10 seconds, and gains a laser drone that attacks up to $t6 enemies within $t5 metres, dealing $d78 physical damage every $t2.5 seconds for $t10 seconds.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Trajectionist",
	"tier": "2",
	"abilities": [
		{
			"name": "Exploitation",
			"gid": 6942500,
			"iid": 7519406,
			"background": 6,
			"cost": 9,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical,Hinder",
			"apply": "Cleanse",
			"description": "Whenever you hit a $sHindered target or critically hit, there is a $t33% chance you also cleanse $t1 detrimental effect from yourself.",
		},
		{
			"name": "Backup Drone",
			"gid": 6942501,
			"iid": 7519370,
			"background": 4,
			"cost": 12,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"cooldown": "90",
			"apply": "Heal",
			"target": "Single",
			"description": "Summons a drone that will follow the defensive target for $t15 seconds. Gives the target a beneficial effect that increases the effectiveness of healing, leech and barrier effects received by $t30%. Every second the drone will heal the defensive target for $h9.",
		},
		{
			"name": "Advantage Me",
			"gid": 6942502,
			"iid": 7519409,
			"background": 6,
			"cost": 16,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical",
			"apply": "HoT,Cleanse",
			"description": "Whenever you critically hit you also gain a heal over time effect, healing for $h10 every second for $t5 seconds.<br> <br>Whenever you critically heal, you cleanse $t1 detrimental effect from your defensive target. This can only happen once per target every $t2 seconds.",
		},
		{
			"name": "Sticky Drone",
			"gid": 6942506,
			"iid": 7519368,
			"background": 4,
			"cost": 21,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"cooldown": "40",
			"apply": "Hinder",
			"description": "Summons a drone that will follow you around for $t40 seconds. You gain a beneficial effect that causes the next $t2 attacks against you to backfire, causing the attacker to become $sHindered and unable to move for $t4 seconds.",
		},
		{
			"name": "Tough Luck",
			"gid": 6942507,
			"iid": 7519404,
			"background": 6,
			"cost": 27,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Critical",
			"apply": "Hinder",
			"description": "Whenever you critically hit, you also cause the target to become $sHindered and rooted to the ground for $t4 seconds. This can only happen once every $t30 seconds.",
		},
		{
			"name": "Win-Win",
			"gid": 6942508,
			"iid": 7519366,
			"background": 4,
			"cost": 34,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "0.5",
			"cooldown": "45",
			"apply": "Heal,Cleanse",
			"target": "PBAoE",
			"description": "PBAoE: Affects you and up to $c5 friends in a $c15 metre radius around you.<br>A PBAoE that heals for $h55 and cleanses $t2 detrimental effects.",
		},
		{
			"name": "Contortionist",
			"gid": 6942509,
			"iid": 7519408,
			"background": 6,
			"cost": 50,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"elite": true,
			"react": "Heal",
			"apply": "Cleanse",
			"description": "Increases all heal, barrier, and leech effects by $h10%. Also, whenever you are $sHindered or $sImpaired, you will immediately remove all detrimental effects. This can only happen every $t25 seconds.",
		},
	]
});

TSW.Wheel[index].cells.push({
	"name": "Positive Reinforcement",
	"tier": "2",
	"abilities": [
		{
			"name": "Greater Good",
			"gid": 6942510,
			"iid": 7519361,
			"background": 4,
			"cost": 9,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"cooldown": "90",
			"react": "Heal,Barrier,Leech",
			"target": "Group",
			"description": "Gives all group members a beneficial effect, which increases the effectiveness of all healing, barriers and leeches done by $t15% for $t10 seconds. This ability does not trigger and is not affected by global recharge time.",
		},
		{
			"name": "Utilitarianism",
			"gid": 6942511,
			"iid": 7519397,
			"background": 6,
			"cost": 12,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Greater Good",
			"description": "Increases the duration of \"Greater Good\" by $t5 seconds. Additionally, while \"Greater Good\" is active, all group members gain a heal over time effect that heals for $h60 or $t1.5% every second, whichever is larger. This value is not affected by your healing power or any other heal increasing effect.",
		},
		{
			"name": "Health Drone",
			"gid": 6942512,
			"iid": 7519360,
			"background": 4,
			"cost": 16,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"cooldown": "4",
			"apply": "Heal,Chain",
			"target": "Chain",
			"description": "Consumes all Pistol resources.<br>Summons a drone that will follow you for $t7 seconds. Every second it will heal allies for $h16-25 with a $uChain heal that can jump up to $c6 nearby friends in a $c8 metre area around you. Heal scales based on the number of resources consumed.",
		},
		{
			"name": "Chain Feed",
			"gid": 6942521,
			"iid": 7519402,
			"background": 6,
			"cost": 21,
			"type": "Passive",
			"active": false,
			"bridge": true,
			"react": "Chain",
			"description": "$uChain abilities are $t10% more effective",
		},
		{
			"name": "Cleansing Drone",
			"gid": 6942526,
			"iid": 7519363,
			"background": 1,
			"cost": 27,
			"type": "Active",
			"active": true,
			"bridge": false,
			"cast": "1",
			"cooldown": "4",
			"consume": "-1",
			"apply": "Cleanse",
			"target": "Single",
			"description": "Consumes all Pistol resources.<br>Summons a drone that will follow the target for $t4 seconds. Every second it will attack the target dealing $d18-37 physical damage, based on the number of resources consumed, and cleanse $t1 detrimental effect from up to $t4 friends in a $t5 metre area around the target. If the target is $sHindered, it will cleanse $t2 detrimental effects.",
		},
		{
			"name": "Drone Support",
			"gid": 6942527,
			"iid": 7519401,
			"background": 6,
			"cost": 34,
			"type": "Passive",
			"active": false,
			"bridge": false,
			"modify": "Cleansing Drone",
			"apply": "Heal",
			"description": "Heals all group members for $h15 when \"Cleansing Drone\" attempts to cleanse. Targets cannot be $sWeakened for $t2 seconds.",
		},
		{
			"name": "Born Leader",
			"gid": 6942528,
			"iid": 7519365,
			"background": 1,
			"cost": 50,
			"type": "Active",
			"active": true,
			"bridge": false,
			"elite": true,
			"cooldown": "25",
			"apply": "Weaken",
			"target": "AoE",
			"description": "GTAoE: Affects up to $c6 friends and $c6 enemies in a $c10 metre radius around you, pulsing every second for $t5 seconds.<br>A pulsing GTAoE attack that lasts $t5 seconds.<br> <br>Up to $c6 allies in the area are healed for $h65 every second.<br> <br>Up to $c6 enemies in a $c10 metre radius will be dealt $d59 physical damage. Affected targets also become $sWeakened by a single stack of the Corrupted effect, which reduces the effectiveness of heal, barrier and leech effects by $t5% per stack for $t10 seconds. This effect can stack up to $t10 times.",
		},
	]
});
